"""Textos da interface a partir do idioma nativo escolhido no primeiro uso."""

from __future__ import annotations

from services.translation_engine import LANGUAGES_DICT


LOCALES = ("pt", "en", "es", "fr", "de", "it", "hi", "ar", "ja", "zh", "ru", "ko")


def _s(
    pt: str,
    en: str,
    es: str,
    fr: str,
    de: str,
    it: str,
    hi: str,
    ar: str,
    ja: str,
    zh: str,
    ru: str,
    ko: str,
) -> dict[str, str]:
    return {
        "pt": pt,
        "en": en,
        "es": es,
        "fr": fr,
        "de": de,
        "it": it,
        "hi": hi,
        "ar": ar,
        "ja": ja,
        "zh": zh,
        "ru": ru,
        "ko": ko,
    }


LANGUAGE_NAMES: dict[str, dict[str, str]] = {
    "Auto": _s("Auto", "Auto", "Auto", "Auto", "Auto", "Auto", "ऑटो", "تلقائي", "自動", "自动", "Авто", "자동"),
    "Português": _s("Português", "Portuguese", "Portugués", "Portugais", "Portugiesisch", "Portoghese", "पुर्तगाली", "البرتغالية", "ポルトガル語", "葡萄牙语", "Португальский", "포르투갈어"),
    "Inglês": _s("Inglês", "English", "Inglés", "Anglais", "Englisch", "Inglese", "अंग्रेज़ी", "الإنجليزية", "英語", "英语", "Английский", "영어"),
    "Espanhol": _s("Espanhol", "Spanish", "Español", "Espagnol", "Spanisch", "Spagnolo", "स्पेनिश", "الإسبانية", "スペイン語", "西班牙语", "Испанский", "스페인어"),
    "Espanhol (Latino)": _s("Espanhol (Latino)", "Spanish (Latin America)", "Español (Latinoamérica)", "Espagnol (Amérique latine)", "Spanisch (Lateinamerika)", "Spagnolo (America Latina)", "स्पेनिश (लैटिन)", "الإسبانية (أمريكا اللاتينية)", "スペイン語（ラテン）", "西班牙语（拉美）", "Испанский (Лат. Америка)", "스페인어(라틴)"),
    "Francês": _s("Francês", "French", "Francés", "Français", "Französisch", "Francese", "फ़्रेंच", "الفرنسية", "フランス語", "法语", "Французский", "프랑스어"),
    "Alemão": _s("Alemão", "German", "Alemán", "Allemand", "Deutsch", "Tedesco", "जर्मन", "الألمانية", "ドイツ語", "德语", "Немецкий", "독일어"),
    "Italiano": _s("Italiano", "Italian", "Italiano", "Italien", "Italienisch", "Italiano", "इतालवी", "الإيطالية", "イタリア語", "意大利语", "Итальянский", "이탈리아어"),
    "Hindi": _s("Hindi", "Hindi", "Hindi", "Hindi", "Hindi", "Hindi", "हिन्दी", "الهندية", "ヒンディー語", "印地语", "Хинди", "힌디어"),
    "Árabe": _s("Árabe", "Arabic", "Árabe", "Arabe", "Arabisch", "Arabo", "अरबी", "العربية", "アラビア語", "阿拉伯语", "Арабский", "아랍어"),
    "Japonês": _s("Japonês", "Japanese", "Japonés", "Japonais", "Japanisch", "Giapponese", "जापानी", "اليابانية", "日本語", "日语", "Японский", "일본어"),
    "Chinês (Mandarim)": _s("Chinês (Mandarim)", "Chinese (Mandarin)", "Chino (Mandarín)", "Chinois (Mandarin)", "Chinesisch (Mandarin)", "Cinese (Mandarino)", "चीनी", "الصينية", "中国語", "中文", "Китайский", "중국어"),
    "Russo": _s("Russo", "Russian", "Ruso", "Russe", "Russisch", "Russo", "रूसी", "الروسية", "ロシア語", "俄语", "Русский", "러시아어"),
    "Coreano": _s("Coreano", "Korean", "Coreano", "Coréen", "Koreanisch", "Coreano", "कोरियाई", "الكورية", "韓国語", "韩语", "Корейский", "한국어"),
}

MODE_LABEL_KEYS = {
    "Híbrido": "mode_hybrid",
    "Nuvem": "mode_cloud",
    "Local": "mode_local",
    "IA": "mode_ai",
}
STT_LABEL_KEYS = {
    "auto": "stt_auto",
    "fast": "stt_fast",
    "balanced": "stt_balanced",
    "accurate": "stt_accurate",
}
GENDER_LABEL_KEYS = {
    "Feminina": "gender_female",
    "Masculina": "gender_male",
}
VOICE_ENGINE_KEYS = {
    "natural": "voice_engine_natural",
    "piper": "voice_engine_piper",
    "windows": "voice_engine_windows",
}
CONTEXT_LABEL_KEYS = {
    "casual": "context_casual",
    "formal": "context_formal",
    "travel": "context_travel",
}

STRINGS: dict[str, dict[str, str]] = {
    "welcome_title": _s("Bem-vindo ao Loon", "Welcome to Loon", "Bienvenido a Loon", "Bienvenue sur Loon", "Willkommen bei Loon", "Benvenuto in Loon", "Loon में आपका स्वागत है", "مرحباً بك في Loon", "Loon へようこそ", "欢迎使用 Loon", "Добро пожаловать в Loon", "Loon에 오신 것을 환영합니다"),
    "welcome_subtitle": _s("Tradução de voz para conversas sem fronteira.", "Voice translation for conversations without borders.", "Traducción de voz para conversar sin fronteras.", "Traduction vocale pour parler sans frontières.", "Sprachübersetzung für Gespräche ohne Grenzen.", "Traduzione vocale per parlare senza confini.", "बिना सीमा के बातचीत के लिए आवाज़ अनुवाद।", "ترجمة صوتية للمحادثات بلا حدود.", "国境のない会話のための音声翻訳。", "用于无国界对话的语音翻译。", "Голосовой перевод для разговоров без границ.", "경계 없는 대화를 위한 음성 번역."),
    "welcome_language": _s("Seu idioma", "Your language", "Tu idioma", "Votre langue", "Ihre Sprache", "La tua lingua", "आपकी भाषा", "لغتك", "あなたの言語", "你的语言", "Ваш язык", "내 언어"),
    "welcome_body": _s("Escolha o idioma e por onde entrar. A tela abre na área em que você estava.", "Choose the language and where to enter. The screen opens in the area you were using.", "Elige el idioma y por dónde entrar. La pantalla abre en el área que estabas usando.", "Choisissez la langue et par où entrer. L'écran s'ouvre là où vous étiez.", "Wählen Sie die Sprache und den Einstieg. Der Bildschirm öffnet den Bereich, in dem Sie waren.", "Scegli la lingua e da dove entrare. La schermata apre l'area che stavi usando.", "भाषा और प्रवेश चुनें। स्क्रीन उसी जगह खुलेगी जहाँ आप थे।", "اختر اللغة ومن أين تدخل. تفتح الشاشة في القسم الذي كنت تستخدمه.", "言語と入る場所を選んでください。前回の場所で開きます。", "选择语言和入口。屏幕会打开你上次所在的区域。", "Выберите язык и откуда войти. Экран откроется там, где вы были.", "언어와 들어갈 곳을 고르세요. 화면은 쓰던 영역에서 열립니다."),
    "welcome_choose": _s("Como você quer começar?", "How do you want to start?", "¿Cómo quieres empezar?", "Comment voulez-vous commencer ?", "Wie möchten Sie beginnen?", "Come vuoi iniziare?", "आप कैसे शुरू करना चाहते हैं?", "كيف تريد أن تبدأ؟", "どこから始めますか？", "你想从哪里开始？", "С чего хотите начать?", "어디서 시작할까요?"),
    "welcome_translate": _s("Iniciar tradução", "Start translation", "Iniciar traducción", "Lancer la traduction", "Übersetzung starten", "Avvia traduzione", "अनुवाद शुरू करें", "بدء الترجمة", "翻訳を開始", "开始翻译", "Начать перевод", "번역 시작"),
    "welcome_translate_hint": _s("Abre a conversa nos dois sentidos, com o contexto e o tom já escolhidos.", "Opens the two-way conversation with the context and pitch you already chose.", "Abre la conversación en los dos sentidos, con el contexto y el tono ya elegidos.", "Ouvre la conversation dans les deux sens, avec le contexte et la hauteur déjà choisis.", "Öffnet das Gespräch in beide Richtungen, mit dem schon gewählten Kontext und Ton.", "Apre la conversazione nei due sensi, con il contesto e il tono già scelti.", "पहले से चुने संदर्भ और स्वर के साथ दोनों दिशाओं में बातचीत खोलता है।", "يفتح المحادثة بالاتجاهين بالسياق والطبقة اللذين اخترتهما.", "選んである場面と声の高さで、双方向の会話を開きます。", "用已选的场景和音高打开双向对话。", "Открывает разговор в обе стороны с уже выбранными контекстом и высотой.", "이미 고른 상황과 음높이로 양방향 대화를 엽니다."),
    "welcome_tests": _s("Testar áudio", "Test audio", "Probar audio", "Tester l'audio", "Audio testen", "Prova audio", "ऑडियो जाँचें", "اختبار الصوت", "音声をテスト", "测试音频", "Проверить звук", "오디오 테스트"),
    "welcome_tests_hint": _s("Abre o microfone, o fone e a saída virtual para conferir o som antes da chamada.", "Opens the microphone, headphones, and virtual output so you can check the sound before a call.", "Abre el micrófono, los auriculares y la salida virtual para comprobar el sonido antes de la llamada.", "Ouvre le micro, le casque et la sortie virtuelle pour vérifier le son avant l'appel.", "Öffnet Mikrofon, Kopfhörer und virtuellen Ausgang, um den Ton vor dem Anruf zu prüfen.", "Apre microfono, cuffie e uscita virtuale per controllare il suono prima della chiamata.", "कॉल से पहले माइक, हेडफ़ोन और वर्चुअल आउटपुट खोलकर आवाज़ जाँचता है।", "يفتح الميكروفون والسماعة والخرج الافتراضي لفحص الصوت قبل المكالمة.", "通話の前にマイク、ヘッドホン、仮想出力で音を確認します。", "通话前打开麦克风、耳机和虚拟输出来检查声音。", "Открывает микрофон, наушники и виртуальный выход, чтобы проверить звук до звонка.", "통화 전에 마이크, 헤드폰, 가상 출력으로 소리를 확인합니다."),
    "welcome_last_translate": _s("Na última vez você estava na tradução.", "Last time you were in translation.", "La última vez estabas en la traducción.", "La dernière fois, vous étiez dans la traduction.", "Zuletzt waren Sie in der Übersetzung.", "L'ultima volta eri nella traduzione.", "पिछली बार आप अनुवाद में थे।", "في المرة السابقة كنت في الترجمة.", "前回は翻訳にいました。", "上次你在翻译页。", "В прошлый раз вы были в переводе.", "지난번에는 번역에 있었습니다."),
    "welcome_last_tests": _s("Na última vez você estava nos testes.", "Last time you were in the tests.", "La última vez estabas en las pruebas.", "La dernière fois, vous étiez dans les tests.", "Zuletzt waren Sie bei den Tests.", "L'ultima volta eri nei test.", "पिछली बार आप परीक्षण में थे।", "في المرة السابقة كنت في الاختبارات.", "前回はテストにいました。", "上次你在测试页。", "В прошлый раз вы были в проверках.", "지난번에는 테스트에 있었습니다."),
    "open_translation": _s("Ir para a tradução", "Go to translation", "Ir a la traducción", "Aller à la traduction", "Zur Übersetzung", "Vai alla traduzione", "अनुवाद पर जाएँ", "الانتقال إلى الترجمة", "翻訳へ移動", "前往翻译", "Перейти к переводу", "번역으로 이동"),
    "tagline": _s("Comunicação sem fronteiras", "Communication without borders", "Comunicación sin fronteras", "Communiquer sans frontières", "Kommunikation ohne Grenzen", "Comunicazione senza confini", "बिना सीमा के संवाद", "تواصل بلا حدود", "国境のないコミュニケーション", "无国界沟通", "Общение без границ", "경계 없는 소통"),
    "tab_translate": _s("Tradução", "Translation", "Traducción", "Traduction", "Übersetzung", "Traduzione", "अनुवाद", "الترجمة", "翻訳", "翻译", "Перевод", "번역"),
    "tab_tests": _s("Testes", "Tests", "Pruebas", "Tests", "Tests", "Test", "परीक्षण", "اختبارات", "テスト", "测试", "Проверки", "테스트"),
    "tab_train": _s("Treino", "Practice", "Práctica", "Entraînement", "Übung", "Pratica", "अभ्यास", "تدريب", "練習", "练习", "Тренировка", "연습"),
    "train_title": _s("Treino de idioma", "Language practice", "Práctica de idioma", "Entraînement linguistique", "Sprachübung", "Pratica linguistica", "भाषा अभ्यास", "تدريب اللغة", "言語の練習", "语言练习", "Языковая тренировка", "언어 연습"),
    "train_subtitle": _s("Fale uma frase. Primeiro você ouve a sua voz, depois a mesma frase traduzida, para comparar.", "Say a phrase. First you hear your own voice, then the same phrase translated, so you can compare.", "Di una frase. Primero oyes tu voz y después la misma frase traducida, para comparar.", "Dites une phrase. Vous entendez d'abord votre voix, puis la même phrase traduite.", "Sagen Sie einen Satz. Zuerst Ihre Stimme, dann derselbe Satz übersetzt.", "Dì una frase. Prima senti la tua voce, poi la stessa frase tradotta.", "एक वाक्य बोलें। पहले अपनी आवाज़, फिर वही वाक्य अनुवादित।", "قل جملة. تسمع صوتك أولاً ثم الجملة نفسها مترجمة.", "文を言います。先に自分の声、次に同じ文の翻訳が聞こえます。", "说一句话。先听到自己的声音，再听到同一句的翻译。", "Скажите фразу. Сначала ваш голос, потом тот же текст в переводе.", "문장을 말하세요. 먼저 내 목소리, 이어서 같은 문장의 번역이 들립니다."),
    "train_target": _s("Traduzir para", "Translate into", "Traducir a", "Traduire vers", "Übersetzen nach", "Traduci in", "इसमें अनुवाद", "ترجم إلى", "翻訳先", "翻译成", "Перевести на", "번역할 언어"),
    "train_you_said": _s("Você disse", "You said", "Dijiste", "Vous avez dit", "Sie sagten", "Hai detto", "आपने कहा", "قلت", "あなたの発言", "你说的", "Вы сказали", "내가 말한 것"),
    "train_translation": _s("Tradução", "Translation", "Traducción", "Traduction", "Übersetzung", "Traduzione", "अनुवाद", "الترجمة", "翻訳", "翻译", "Перевод", "번역"),
    "train_translation_idle": _s("A tradução aparece aqui e sai em voz logo depois da sua.", "The translation appears here and is spoken right after yours.", "La traducción aparece aquí y se oye justo después de tu voz.", "La traduction apparaît ici et se dit juste après votre voix.", "Die Übersetzung erscheint hier und ertönt gleich nach Ihrer Stimme.", "La traduzione appare qui e si sente subito dopo la tua voce.", "अनुवाद यहाँ दिखेगा और आपकी आवाज़ के ठीक बाद सुनाई देगा।", "تظهر الترجمة هنا وتُنطق مباشرة بعد صوتك.", "翻訳はここに出て、あなたの声の直後に流れます。", "翻译显示在这里，并在你的声音之后播出。", "Перевод появится здесь и прозвучит сразу после вашего голоса.", "번역이 여기에 나오고, 내 목소리 바로 뒤에 들립니다."),
    "train_translated_voice": _s("Agora a voz traduzida...", "Now the translated voice...", "Ahora la voz traducida...", "Maintenant la voix traduite...", "Jetzt die übersetzte Stimme...", "Ora la voce tradotta...", "अब अनुवादित आवाज़...", "الآن الصوت المترجم...", "次は翻訳した声...", "现在是翻译后的声音...", "Теперь переведённый голос...", "이제 번역된 목소리..."),
    "train_language": _s("Idioma que você está treinando", "Language you are practicing", "Idioma que practicas", "Langue que vous entraînez", "Sprache, die Sie üben", "Lingua che stai praticando", "जिस भाषा का अभ्यास कर रहे हैं", "اللغة التي تتدرب عليها", "練習している言語", "正在练习的语言", "Язык, который вы тренируете", "연습 중인 언어"),
    "train_speak": _s("Falar e ouvir", "Speak and listen", "Hablar y escuchar", "Parler et écouter", "Sprechen und hören", "Parla e ascolta", "बोलें और सुनें", "تكلم واستمع", "話して聞く", "说并聆听", "Сказать и услышать", "말하고 듣기"),
    "train_idle_text": _s("A frase que você disser aparece aqui.", "The phrase you say appears here.", "La frase que digas aparece aquí.", "La phrase dite apparaît ici.", "Der gesprochene Satz erscheint hier.", "La frase detta appare qui.", "आपका वाक्य यहाँ दिखेगा।", "ستظهر عبارتك هنا.", "話した文がここに出ます。", "你说的句子会出现在这里。", "Сказанная фраза появится здесь.", "말한 문장이 여기에 나옵니다."),
    "train_listening": _s("Pode falar.", "You can speak.", "Puedes hablar.", "Vous pouvez parler.", "Sie können sprechen.", "Puoi parlare.", "बोल सकते हैं।", "يمكنك التحدث.", "話してください。", "请说话。", "Можете говорить.", "말하세요."),
    "train_empty": _s("Não ouvi uma frase. Tente de novo, mais perto do microfone.", "I did not hear a phrase. Try again, closer to the microphone.", "No oí una frase. Inténtalo de nuevo, más cerca del micrófono.", "Je n'ai pas entendu de phrase. Réessayez plus près du micro.", "Kein Satz gehört. Versuchen Sie es näher am Mikrofon.", "Non ho sentito una frase. Riprova più vicino al microfono.", "वाक्य नहीं सुना। माइक के पास से फिर बोलें।", "لم أسمع جملة. أعد المحاولة أقرب إلى الميكروفون.", "文が聞こえませんでした。マイクに近づいて再試行してください。", "没有听到句子。请靠近麦克风再试。", "Фраза не слышна. Повторите ближе к микрофону.", "문장이 들리지 않았습니다. 마이크에 더 가까이 다시 말하세요."),
    "train_replay": _s("Repetindo a sua voz...", "Playing your voice back...", "Repitiendo tu voz...", "Relecture de votre voix...", "Ihre Stimme wird wiederholt...", "Ripetizione della tua voce...", "आपकी आवाज़ दोहरा रहे हैं...", "إعادة صوتك...", "あなたの声を再生しています...", "正在重放你的声音...", "Повтор вашего голоса...", "내 목소리를 다시 재생합니다..."),
    "train_done": _s("Pronto. Fale de novo quando quiser.", "Done. Speak again whenever you want.", "Listo. Habla otra vez quando quieras.", "Terminé. Reparlez quand vous voulez.", "Fertig. Sprechen Sie wieder, wann Sie wollen.", "Fatto. Parla di nuovo quando vuoi.", "हो गया। जब चाहें फिर बोलें।", "تم. تكلم مرة أخرى متى شئت.", "完了。いつでももう一度話せます。", "完成。想说时再来一次。", "Готово. Говорите снова, когда захотите.", "끝났습니다. 원할 때 다시 말하세요."),
    "tips_translate_title": _s("Dica da chamada", "Call tip", "Consejo de la llamada", "Conseil d'appel", "Anruf-Tipp", "Suggerimento chiamata", "कॉल सुझाव", "نصيحة المكالمة", "通話のヒント", "通话提示", "Совет по звонку", "통화 팁"),
    "tips_translate_body": _s("Iniciante: escolha o microfone, o fone e o CABLE Input antes de iniciar. Veterano: o contexto Casual muda gírias; o tom da voz muda a altura sem alterar a duração.", "Beginner: choose the microphone, headphones, and CABLE Input before starting. Veteran: Casual context changes slang; voice pitch changes the height without changing the length.", "Principiante: elige micrófono, auriculares y CABLE Input antes de iniciar. Avanzado: el contexto informal cambia la jerga; el tono cambia la altura.", "Débutant : choisissez micro, casque et CABLE Input avant de lancer. Averti : le contexte décontracté change l'argot ; la hauteur change le ton.", "Einsteiger: Mikrofon, Kopfhörer und CABLE Input vor dem Start wählen. Erfahren: Locker ändert Umgangssprache; die Tonhöhe ändert die Höhe.", "Principiante: scegli microfono, cuffie e CABLE Input prima di avviare. Esperto: il contesto informale cambia il gergo; il tono cambia l'altezza.", "शुरुआती: माइक, हेडफ़ोन और CABLE Input चुनें। अनुभवी: अनौपचारिक संदर्भ मुहावरे बदलता है; स्वर ऊँचाई बदलता है।", "مبتدئ: اختر الميكروفون والسماعة وCABLE Input قبل البدء. خبير: السياق العفوي يغيّر العامية؛ الطبقة تغيّر الارتفاع.", "初心者: 開始前にマイク、ヘッドホン、CABLE Inputを選ぶ。慣れた人: カジュアルは俗語を変え、音高は高さを変える。", "新手：开始前选好麦克风、耳机和 CABLE Input。熟手：随意场景会改俚语，音高只改高低。", "Новичок: выберите микрофон, наушники и CABLE Input. Опытный: разговорный контекст меняет сленг; высота меняет тон.", "초보: 시작 전에 마이크, 헤드폰, CABLE Input을 고르세요. 숙련: 일상 상황은 속어를 바꾸고, 음높이는 높이만 바꿉니다."),
    "tips_tests_title": _s("Dica dos testes", "Tests tip", "Consejo de las pruebas", "Conseil des tests", "Test-Tipp", "Suggerimento test", "परीक्षण सुझाव", "نصيحة الاختبارات", "テストのヒント", "测试提示", "Совет по проверкам", "테스트 팁"),
    "tips_tests_body": _s("Iniciante: Ouvir nível mostra a onda; fale e veja as barras subirem. Grave só depois disso. Veterano: se o fone Bluetooth falhar, o som vai para os alto-falantes.", "Beginner: Listen to level shows the wave; speak and watch the bars rise. Record only after that. Veteran: if the Bluetooth headphones fail, the sound goes to the speakers.", "Principiante: Escuchar nivel muestra la onda. Graba después. Avanzado: si el Bluetooth falla, el sonido va a los altavoces.", "Débutant : Écouter le niveau montre l'onde. Enregistrez ensuite. Averti : si le Bluetooth échoue, le son va aux haut-parleurs.", "Einsteiger: Pegel zeigt die Welle. Danach aufnehmen. Erfahren: scheitert Bluetooth, geht der Ton an die Lautsprecher.", "Principiante: il livello mostra l'onda. Registra dopo. Esperto: se il Bluetooth fallisce, il suono va agli altoparlanti.", "शुरुआती: स्तर लहर दिखाता है। उसके बाद रिकॉर्ड करें। अनुभवी: ब्लूटूथ फेल हो तो आवाज़ स्पीकर पर जाती है।", "مبتدئ: مستوى الصوت يُظهر الموجة. سجّل بعد ذلك. خبير: إذا فشل البلوتوث يذهب الصوت إلى المكبرات.", "初心者: レベルが波形を出します。その後に録音。慣れた人: Bluetoothが失敗するとスピーカーへ。", "新手：电平会显示波形，然后再录音。熟手：蓝牙失败时声音会转到扬声器。", "Новичок: уровень показывает волну. Потом записывайте. Опытный: если Bluetooth отказывает, звук идёт в колонки.", "초보: 레벨이 파형을 보여 줍니다. 그다음 녹음하세요. 숙련: 블루투스가 실패하면 스피커로 갑니다."),
    "tips_train_title": _s("Dica do treino", "Practice tip", "Consejo de la práctica", "Conseil d'entraînement", "Übungs-Tipp", "Suggerimento pratica", "अभ्यास सुझाव", "نصيحة التدريب", "練習のヒント", "练习提示", "Совет по тренировке", "연습 팁"),
    "tips_train_body": _s("Iniciante: uma frase curta. Você ouve a sua voz e, em seguida, a tradução falada. Veterano: o idioma da esquerda é o que você fala; o da direita é a voz que vem depois.", "Beginner: a short phrase. You hear your voice and then the spoken translation. Veteran: the language on the left is what you speak; the one on the right is the voice that follows.", "Principiante: una frase corta. Oyes tu voz y luego la traducción hablada. Avanzado: izquierda es lo que hablas; derecha es la voz que sigue.", "Débutant : une phrase courte. Vous entendez votre voix, puis la traduction parlée. Averti : à gauche ce que vous dites, à droite la voix qui suit.", "Einsteiger: ein kurzer Satz. Sie hören Ihre Stimme, dann die gesprochene Übersetzung. Erfahren: links Ihre Sprache, rechts die folgende Stimme.", "Principiante: una frase breve. Senti la tua voce e poi la traduzione parlata. Esperto: a sinistra ciò che dici, a destra la voce che segue.", "शुरुआती: छोटा वाक्य। पहले अपनी आवाज़, फिर बोला गया अनुवाद। अनुभवी: बायाँ भाषा आप बोलते हैं; दायाँ बाद की आवाज़ है।", "مبتدئ: جملة قصيرة. تسمع صوتك ثم الترجمة المنطوقة. خبير: اليسار ما تقوله واليمين الصوت الذي يليه.", "初心者: 短い文。自分の声のあと翻訳の声。慣れた人: 左が話す言語、右が続く声。", "新手：说短句。先听自己的声音，再听翻译。熟手：左边是你说的语言，右边是随后的声音。", "Новичок: короткая фраза. Сначала ваш голос, потом перевод. Опытный: слева язык речи, справа голос, который следует.", "초보: 짧은 문장. 내 목소리 다음 번역된 목소리가 들립니다. 숙련: 왼쪽은 말하는 언어, 오른쪽은 이어지는 목소리입니다."),
    "tips_settings_title": _s("Dica das configurações", "Settings tip", "Consejo de ajustes", "Conseil des réglages", "Einstellungs-Tipp", "Suggerimento impostazioni", "सेटिंग सुझाव", "نصيحة الإعدادات", "設定のヒント", "设置提示", "Совет по настройкам", "설정 팁"),
    "tips_settings_body": _s("Iniciante: o idioma da interface só muda os textos. O idioma da conversa fica nos painéis. Veterano: Local funciona sem internet; Nuvem pede rede para a voz.", "Beginner: the interface language only changes the texts. The conversation language is in the panels. Veteran: Local works offline; Cloud needs a network for the voice.", "Principiante: el idioma de la interfaz solo cambia los textos. Avanzado: Local funciona sin internet; Nube pide red.", "Débutant : la langue de l'interface ne change que les textes. Averti : Local marche hors ligne ; Nuage demande le réseau.", "Einsteiger: die Oberflächensprache ändert nur Texte. Erfahren: Lokal geht offline; Cloud braucht Netz.", "Principiante: la lingua dell'interfaccia cambia solo i testi. Esperto: Locale funziona offline; Cloud chiede la rete.", "शुरुआती: इंटरफ़ेस भाषा केवल लेख बदलती है। अनुभवी: लोकल ऑफ़लाइन चलता है; क्लाउड को नेट चाहिए।", "مبتدئ: لغة الواجهة تغيّر النصوص فقط. خبير: المحلي يعمل دون نت؛ السحابة تحتاج شبكة.", "初心者: 画面の言語は文言だけを変える。慣れた人: ローカルはオフライン、クラウドはネットが必要。", "新手：界面语言只改文字。熟手：本地可离线；云端语音需要网络。", "Новичок: язык интерфейса меняет только тексты. Опытный: локальный режим офлайн; облаку нужна сеть.", "초보: 화면 언어는 글만 바꿉니다. 숙련: 로컬은 오프라인, 클라우드는 네트워크가 필요합니다."),
    "tutorial_button": _s("Tutorial", "Tutorial", "Tutorial", "Tutoriel", "Anleitung", "Tutorial", "ट्यूटोरियल", "الدليل", "チュートリアル", "教程", "Учебник", "튜토리얼"),
    "tutorial_title": _s("Como usar o Loon", "How to use Loon", "Cómo usar Loon", "Comment utiliser Loon", "So nutzen Sie Loon", "Come usare Loon", "Loon कैसे उपयोग करें", "كيف تستخدم Loon", "Loonの使い方", "如何使用 Loon", "Как пользоваться Loon", "Loon 사용법"),
    "tutorial_intro": _s("Cada parte tem um caminho curto para quem começa e um detalhe para quem já usa.", "Each part has a short path for beginners and a detail for people who already use it.", "Cada parte tiene un camino corto para quien empieza y un detalle para quien ya lo usa.", "Chaque partie a un chemin court pour débuter et un détail pour qui l'utilise déjà.", "Jeder Teil hat einen kurzen Weg für Einsteiger und ein Detail für Geübte.", "Ogni parte ha una via breve per chi inizia e un dettaglio per chi già usa.", "हर भाग में शुरुआत का छोटा रास्ता और जानने वालों के लिए विवरण है।", "لكل جزء طريق قصير للمبتدئ وتفصيل لمن يستخدمه.", "各部分に初心者向けの短い手順と、慣れた人向けの詳細があります。", "每一部分都有给新手的短路径，也有给熟手的细节。", "В каждой части короткий путь для новичка и деталь для тех, кто уже пользуется.", "각 부분에는 초보를 위한 짧은 길과 익숙한 사람을 위한 세부 사항이 있습니다."),
    "tutorial_translate_title": _s("Chamada", "Call", "Llamada", "Appel", "Anruf", "Chiamata", "कॉल", "المكالمة", "通話", "通话", "Звонок", "통화"),
    "tutorial_translate_body": _s("1. Na barra, escolha o idioma da tela.\n2. No painel da esquerda, o idioma que você fala e para qual traduzir, o microfone e o CABLE Input.\n3. No painel da direita, o idioma de quem liga, o fone e o CABLE Output.\n4. Iniciar tradução. Para parar, o mesmo botão.\nQuem já usa: contexto Casual, Formal ou Viagem muda o tom; o controle de tom deixa a voz mais aguda ou grave.", "1. In the bar, choose the screen language.\n2. On the left panel, the language you speak, the translation, the microphone, and CABLE Input.\n3. On the right panel, the caller's language, the headphones, and CABLE Output.\n4. Start translation. The same button stops it.\nIf you already use it: Casual, Formal, or Travel changes the tone; the pitch control makes the voice higher or deeper.", "1. En la barra, el idioma de la pantalla.\n2. A la izquierda, tu idioma, la traducción, el micrófono y CABLE Input.\n3. A la derecha, el idioma de quien llama, los auriculares y CABLE Output.\n4. Iniciar. El mismo botón detiene.\nSi ya lo usas: Informal, Formal o Viaje cambia el tono.", "1. Dans la barre, la langue de l'écran.\n2. À gauche, votre langue, la traduction, le micro et CABLE Input.\n3. À droite, la langue de l'appelant, le casque et CABLE Output.\n4. Lancer. Le même bouton arrête.\nSi vous l'utilisez déjà : le contexte change le ton.", "1. In der Leiste die Sprache der Oberfläche.\n2. Links Ihre Sprache, die Übersetzung, Mikrofon und CABLE Input.\n3. Rechts die Sprache des Anrufers, Kopfhörer und CABLE Output.\n4. Starten. Dieselbe Schaltfläche stoppt.\nWer es schon nutzt: der Kontext ändert den Ton.", "1. Nella barra, la lingua dello schermo.\n2. A sinistra la tua lingua, la traduzione, il microfono e CABLE Input.\n3. A destra la lingua di chi chiama, le cuffie e CABLE Output.\n4. Avvia. Lo stesso pulsante ferma.\nChi già lo usa: il contesto cambia il tono.", "1. बार में स्क्रीन की भाषा चुनें।\n2. बाएँ पैनल में अपनी भाषा, अनुवाद, माइक और CABLE Input।\n3. दाएँ पैनल में कॉलर की भाषा, हेडफ़ोन और CABLE Output।\n4. अनुवाद शुरू करें। वही बटन रोकता है।", "1. في الشريط اختر لغة الشاشة.\n2. يساراً لغتك والترجمة والميكروفون وCABLE Input.\n3. يميناً لغة المتصل والسماعة وCABLE Output.\n4. ابدأ الترجمة. الزر نفسه يوقفها.", "1. バーで画面の言語を選ぶ。\n2. 左に自分の言語、翻訳、マイク、CABLE Input。\n3. 右に相手の言語、ヘッドホン、CABLE Output。\n4. 翻訳を開始。同じボタンで停止。", "1. 在栏中选择界面语言。\n2. 左侧是你说的语言、译文、麦克风和 CABLE Input。\n3. 右侧是对方的语言、耳机和 CABLE Output。\n4. 开始翻译。同一个按钮可停止。", "1. На панели выберите язык экрана.\n2. Слева ваш язык, перевод, микрофон и CABLE Input.\n3. Справа язык собеседника, наушники и CABLE Output.\n4. Начать перевод. Та же кнопка останавливает.", "1. 막대에서 화면 언어를 고릅니다.\n2. 왼쪽은 내 언어, 번역, 마이크, CABLE Input.\n3. 오른쪽은 상대 언어, 헤드폰, CABLE Output.\n4. 번역 시작. 같은 버튼으로 멈춥니다."),
    "tutorial_tests_title": _s("Testes", "Tests", "Pruebas", "Tests", "Tests", "Test", "परीक्षण", "الاختبارات", "テスト", "测试", "Проверки", "테스트"),
    "tutorial_tests_body": _s("Ouvir nível: fale e veja a onda. Gravar: três segundos saem no fone. Ouvir o tom e a amostra conferem a voz traduzida. Tocar na saída virtual manda um sinal ao cabo, não ao fone. Faça isso antes da primeira chamada.", "Listen to level: speak and watch the wave. Record: three seconds play in the headphones. Tone and sample check the translated voice. Play on virtual output sends a signal to the cable, not the headphones. Do this before the first call.", "Escuchar nivel muestra la onda. Grabar reproduce tres segundos. La salida virtual va al cable. Hazlo antes de la primera llamada.", "Écouter le niveau montre l'onde. Enregistrer joue trois secondes. La sortie virtuelle va au câble. Faites-le avant le premier appel.", "Pegel zeigt die Welle. Aufnehmen spielt drei Sekunden. Der virtuelle Ausgang geht ans Kabel. Vor dem ersten Anruf prüfen.", "Il livello mostra l'onda. Registra riproduce tre secondi. L'uscita virtuale va al cavo. Fallo prima della prima chiamata.", "स्तर लहर दिखाता है। रिकॉर्ड तीन सेकंड बजाता है। वर्चुअल आउटपुट केबल पर जाता है। पहली कॉल से पहले करें।", "المستوى يُظهر الموجة. التسجيل يشغّل ثلاث ثوان. الخرج الافتراضي يذهب إلى الكابل. افعله قبل أول مكالمة.", "レベルは波形です。録音は3秒を再生します。仮想出力はケーブルへ。最初の通話の前に。", "电平显示波形。录音播放三秒。虚拟输出送到线缆。第一次通话前先做。", "Уровень показывает волну. Запись играет три секунды. Виртуальный выход идёт в кабель. Сделайте это до первого звонка.", "레벨은 파형입니다. 녹음은 3초를 재생합니다. 가상 출력은 케이블로 갑니다. 첫 통화 전에 하세요."),
    "tutorial_train_title": _s("Treino", "Practice", "Práctica", "Entraînement", "Übung", "Pratica", "अभ्यास", "التدريب", "練習", "练习", "Тренировка", "연습"),
    "tutorial_train_body": _s("Escolha o idioma que você fala e o idioma da comparação. Aperte Falar e ouvir. O Loon mostra as duas frases, toca a sua voz e em seguida a voz traduzida. Não entra na chamada. Repita até as duas frases ficarem claras.", "Choose the language you speak and the comparison language. Press Speak and listen. Loon shows both phrases, plays your voice, then the translated voice. It does not join the call. Repeat until both phrases are clear.", "Elige el idioma que hablas y el de la comparación. Pulsa Hablar y escuchar. Muestra las dos frases, tu voz y luego la traducida. No entra en la llamada.", "Choisissez votre langue et celle de la comparaison. Appuyez sur Parler et écouter. Les deux phrases s'affichent, puis votre voix et la voix traduite. Pas d'appel.", "Wählen Sie Ihre Sprache und die Vergleichssprache. Tippen Sie auf Sprechen und hören. Beide Sätze erscheinen, dann Ihre Stimme und die übersetzte. Kein Anruf.", "Scegli la lingua che parli e quella del confronto. Premi Parla e ascolta. Mostra le due frasi, la tua voce e poi quella tradotta. Non entra in chiamata.", "अपनी भाषा और तुलना की भाषा चुनें। बोलें और सुनें दबाएँ। दोनों वाक्य दिखेंगे, फिर आपकी आवाज़ और अनुवादित आवाज़। कॉल में नहीं जाता।", "اختر لغتك ولغة المقارنة. اضغط تكلم واستمع. تظهر الجملتان ثم صوتك ثم الصوت المترجم. لا يدخل المكالمة.", "話す言語と比較の言語を選び、話して聞くを押します。二つの文、自分の声、翻訳の声の順です。通話には入りません。", "选择你说的语言和对照语言。点说并聆听。先显示两句，再播放你的声音和翻译的声音。不进入通话。", "Выберите язык речи и язык сравнения. Нажмите Сказать и услышать. Появятся обе фразы, затем ваш голос и переведённый. В звонок не входит.", "말하는 언어와 비교 언어를 고르고 말하고 듣기를 누르세요. 두 문장이 나오고, 내 목소리 다음 번역된 목소리가 들립니다. 통화에는 들어가지 않습니다."),
    "tutorial_settings_title": _s("Configurações", "Settings", "Ajustes", "Réglages", "Einstellungen", "Impostazioni", "सेटिंग", "الإعدادات", "設定", "设置", "Настройки", "설정"),
    "tutorial_settings_body": _s("A barra lateral guarda o idioma da tela, Local ou Nuvem, o contexto, a voz e o tom. Atualizar dispositivos relê microfone, fone e cabo. Pacotes de idiomas baixam a tradução offline. O tutorial pode ser aberto de novo por este botão sempre que uma aba parecer estranha.", "The sidebar keeps the screen language, Local or Cloud, the context, the voice, and the pitch. Refresh devices rereads microphone, headphones, and cable. Language packs download the offline translation. This tutorial can be opened again whenever a tab feels unclear.", "La barra guarda el idioma, Local o Nube, el contexto, la voz y el tono. Actualizar dispositivos relee los aparatos. Los paquetes bajan la traducción sin internet.", "La barre garde la langue, Local ou Nuage, le contexte, la voix et la hauteur. Actualiser relit les appareils. Les packs téléchargent la traduction hors ligne.", "Die Leiste speichert Sprache, Lokal oder Cloud, Kontext, Stimme und Tonhöhe. Geräte aktualisieren liest die Apparate neu. Sprachpakete laden die Offline-Übersetzung.", "La barra tiene lingua, Locale o Cloud, contesto, voce e tono. Aggiorna dispositivi rilegge gli apparecchi. I pacchetti scaricano la traduzione offline.", "साइडबार भाषा, लोकल या क्लाउड, संदर्भ, आवाज़ और स्वर रखता है। डिवाइस रीफ़्रेश उपकरण फिर पढ़ता है।", "الشريط يحفظ اللغة والمحلي أو السحابة والسياق والصوت والطبقة. تحديث الأجهزة يعيد قراءة الأدوات.", "サイドバーは言語、ローカルかクラウド、場面、声、高さを覚えます。デバイス更新は機器を読み直します。", "侧栏保存界面语言、本地或云端、场景、声音和音高。刷新设备会重读设备。语言包下载离线翻译。", "Боковая панель хранит язык, локальный или облачный режим, контекст, голос и высоту. Обновление устройств перечитывает аппараты.", "사이드바는 화면 언어, 로컬 또는 클라우드, 상황, 음성, 음높이를 저장합니다. 장치 새로고침은 장치를 다시 읽습니다."),
    "header_title": _s("Tradução simultânea", "Live translation", "Traducción simultánea", "Traduction simultanée", "Simultane Übersetzung", "Traduzione simultanea", "साथ-साथ अनुवाद", "ترجمة فورية", "同時翻訳", "同声翻译", "Синхронный перевод", "동시 번역"),
    "header_subtitle": _s("Configure os dois sentidos da conversa e inicie quando estiver pronto.", "Set both directions of the conversation and start when you are ready.", "Configura los dos sentidos de la conversación e inicia cuando estés listo.", "Réglez les deux sens de la conversation et lancez quand vous êtes prêt.", "Legen Sie beide Gesprächsrichtungen fest und starten Sie, wenn Sie bereit sind.", "Imposta i due sensi della conversazione e avvia quando sei pronto.", "बातचीत की दोनों दिशाएँ सेट करें और तैयार होने पर शुरू करें।", "اضبط اتجاهي المحادثة وابدأ عندما تكون جاهزاً.", "会話の両方向を設定し、準備ができたら開始します。", "设置对话的两个方向，准备好后即可开始。", "Настройте оба направления разговора и начните, когда будете готовы.", "대화의 두 방향을 설정하고 준비되면 시작하세요."),
    "section_processing": _s("PROCESSAMENTO", "PROCESSING", "PROCESAMIENTO", "TRAITEMENT", "VERARBEITUNG", "ELABORAZIONE", "प्रोसेसिंग", "المعالجة", "処理", "处理", "ОБРАБОТКА", "처리"),
    "voice_label": _s("Gênero da voz", "Voice gender", "Género de la voz", "Genre de la voix", "Stimmgeschlecht", "Genere della voce", "आवाज़ का लिंग", "جنس الصوت", "声の性別", "语音性别", "Пол голоса", "음성 성별"),
    "voice_engine_label": _s("Qualidade da voz", "Voice quality", "Calidad de la voz", "Qualité de la voix", "Stimmqualität", "Qualità della voce", "आवाज़ की गुणवत्ता", "جودة الصوت", "声の質", "语音质量", "Качество голоса", "음성 품질"),
    "voice_engine_natural": _s("Natural online (recomendada)", "Natural online (recommended)", "Natural en línea (recomendada)", "Naturelle en ligne (recommandée)", "Natürlich online (empfohlen)", "Naturale online (consigliata)", "ऑनलाइन प्राकृतिक (अनुशंसित)", "طبيعي عبر الإنترنت (موصى به)", "オンライン自然（推奨）", "在线自然（推荐）", "Естественный онлайн (рекомендуется)", "온라인 자연스러움 (권장)"),
    "voice_engine_piper": _s("Natural local (Piper)", "Local neural (Piper)", "Natural local (Piper)", "Naturelle locale (Piper)", "Lokal neuronal (Piper)", "Naturale locale (Piper)", "स्थानीय प्राकृतिक (Piper)", "محلي طبيعي (Piper)", "ローカル自然（Piper）", "本地自然（Piper）", "Локальный нейро (Piper)", "로컬 자연스러움 (Piper)"),
    "voice_engine_windows": _s("Windows (offline)", "Windows (offline)", "Windows (sin conexión)", "Windows (hors ligne)", "Windows (offline)", "Windows (offline)", "Windows (ऑफ़लाइन)", "Windows (دون اتصال)", "Windows（オフライン）", "Windows（离线）", "Windows (офлайн)", "Windows (오프라인)"),
    "voice_engine_hint": _s("Online usa vozes neurais da Microsoft. Piper baixa uma voz neural no seu PC (~60 MB, uma vez) e funciona sem internet. Windows é a voz clássica do sistema, mais robótica.", "Online uses Microsoft neural voices. Piper downloads a neural voice to your PC (~60 MB, once) and then works offline. Windows is the classic system voice, more robotic.", "Online usa voces neurales de Microsoft. Piper baja una voz neural a tu PC (~60 MB, una vez) y luego funciona sin red. Windows es la voz clásica, más robótica.", "En ligne : voix neuronales Microsoft. Piper télécharge une voix locale (~60 Mo, une fois) puis marche hors ligne. Windows est la voix classique, plus robotique.", "Online nutzt Microsoft-Neuralstimmen. Piper lädt einmal ~60 MB auf den PC und läuft danach offline. Windows ist die klassische Systemstimme.", "Online usa voci neurali Microsoft. Piper scarica una voce nel PC (~60 MB, una volta) e poi funziona offline. Windows è la voce classica, più robotica.", "ऑनलाइन Microsoft तंत्रिका आवाज़। Piper ~60 MB एक बार डाउनलोड कर ऑफ़लाइन चलता है। Windows सिस्टम आवाज़ रोबोट जैसी है।", "عبر الإنترنت أصوات Microsoft العصبية. Piper ينزّل صوتاً محلياً (~60MB مرة واحدة) ثم يعمل دون نت. Windows هو الصوت الكلاسيكي الأكثر آلية.", "オンラインは Microsoft のニューラル音声。Piper は約60MBを一度だけ入れ、以後オフライン。Windows は機械的なシステム音声です。", "在线使用微软神经网络语音。Piper 会一次性下载约 60MB 到电脑，之后可离线。Windows 是更机械的系统语音。", "Онлайн — нейросети Microsoft. Piper один раз качает ~60 МБ на ПК и дальше офлайн. Windows — классический роботный голос.", "온라인은 Microsoft 신경망 음성입니다. Piper는 약 60MB를 한 번 받은 뒤 오프라인으로 씁니다. Windows는 더 기계적인 시스템 음성입니다."),
    "pitch_label": _s("Tom da voz", "Voice pitch", "Tono de la voz", "Hauteur de la voix", "Stimmton", "Tono della voce", "आवाज़ का स्वर", "طبقة الصوت", "声の高さ", "音高", "Высота голоса", "음성 높낮이"),
    "pitch_higher": _s("mais agudo", "higher", "más agudo", "plus aigu", "höher", "più acuto", "ऊँचा", "أعلى", "高い", "更高", "выше", "더 높게"),
    "pitch_lower": _s("mais grave", "deeper", "más grave", "plus grave", "tiefer", "più grave", "नीचा", "أعمق", "低い", "更低", "ниже", "더 낮게"),
    "pitch_natural": _s("natural", "natural", "natural", "naturel", "natürlich", "naturale", "सामान्य", "طبيعي", "そのまま", "自然", "обычно", "기본"),
    "context_label": _s("Contexto da conversa", "Conversation context", "Contexto de la conversación", "Contexte de la conversation", "Gesprächskontext", "Contesto della conversazione", "बातचीत का संदर्भ", "سياق المحادثة", "会話の場面", "对话场景", "Контекст разговора", "대화 상황"),
    "context_casual": _s("Casual / Gírias", "Casual / Slang", "Informal / Jerga", "Décontracté / Argot", "Locker / Umgangssprache", "Informale / Gergo", "अनौपचारिक / बोलचाल", "عفوي / عامية", "カジュアル / 俗語", "随意 / 俚语", "Разговорный / Сленг", "일상 / 속어"),
    "context_formal": _s("Formal / Corporativo", "Formal / Business", "Formal / Corporativo", "Formel / Entreprise", "Formell / Geschäftlich", "Formale / Aziendale", "औपचारिक / कॉर्पोरेट", "رسمي / عمل", "フォーマル / ビジネス", "正式 / 商务", "Официальный / Деловой", "격식 / 비즈니스"),
    "context_travel": _s("Viagem", "Travel", "Viaje", "Voyage", "Reise", "Viaggio", "यात्रा", "سفر", "旅行", "旅行", "Путешествие", "여행"),
    "context_hint": _s("Ajusta gírias, formalidade e expressões de viagem.", "Tunes slang, formality, and travel expressions.", "Ajusta jerga, formalidad y expresiones de viaje.", "Règle l'argot, le ton formel et les expressions de voyage.", "Steuert Umgangssprache, Formalität und Reisewendungen.", "Regola gergo, formalità ed espressioni di viaggio.", "बोलचाल, औपचारिकता और यात्रा की अभिव्यक्तियाँ सेट करता है।", "يضبط العامية والرسمية وتعابير السفر.", "俗語、敬語、旅行表現の調子を合わせます。", "调整俚语、正式程度和旅行用语。", "Настраивает сленг, официальность и дорожные выражения.", "속어, 격식, 여행 표현의 말투를 맞춥니다."),
    "ui_language": _s("Idioma da interface", "Interface language", "Idioma de la interfaz", "Langue de l'interface", "Sprache der Oberfläche", "Lingua dell'interfaccia", "इंटरफ़ेस की भाषा", "لغة الواجهة", "画面の言語", "界面语言", "Язык интерфейса", "인터페이스 언어"),
    "save_history": _s("Salvar histórico local", "Save local history", "Guardar historial local", "Enregistrer l'historique local", "Lokalen Verlauf speichern", "Salva cronologia locale", "स्थानीय इतिहास सहेजें", "حفظ السجل محلياً", "ローカル履歴を保存", "保存本地历史", "Сохранять локальную историю", "로컬 기록 저장"),
    "monitor_self": _s("Ouvir minha tradução", "Hear my translation", "Oír mi traducción", "Entendre ma traduction", "Meine Übersetzung hören", "Ascoltare la mia traduzione", "अपना अनुवाद सुनें", "سماع ترجمتي", "自分の翻訳を聞く", "听自己的翻译", "Слушать свой перевод", "내 번역 듣기"),
    "refresh_devices": _s("Atualizar dispositivos", "Refresh devices", "Actualizar dispositivos", "Actualiser les appareils", "Geräte aktualisieren", "Aggiorna dispositivi", "डिवाइस रीफ़्रेश करें", "تحديث الأجهزة", "デバイスを更新", "刷新设备", "Обновить устройства", "장치 새로고침"),
    "language_packs": _s("Pacotes de idiomas", "Language packs", "Paquetes de idiomas", "Packs de langues", "Sprachpakete", "Pacchetti lingua", "भाषा पैक", "حزم اللغات", "言語パック", "语言包", "Языковые пакеты", "언어 팩"),
    "start": _s("Iniciar tradução", "Start translation", "Iniciar traducción", "Lancer la traduction", "Übersetzung starten", "Avvia traduzione", "अनुवाद शुरू करें", "بدء الترجمة", "翻訳を開始", "开始翻译", "Начать перевод", "번역 시작"),
    "stop": _s("Parar tradução", "Stop translation", "Detener traducción", "Arrêter la traduction", "Übersetzung stoppen", "Ferma traduzione", "अनुवाद रोकें", "إيقاف الترجمة", "翻訳を停止", "停止翻译", "Остановить перевод", "번역 중지"),
    "stopping": _s("Parando...", "Stopping...", "Deteniendo...", "Arrêt...", "Stoppen...", "Arresto...", "रोक रहे हैं...", "جارٍ الإيقاف...", "停止しています...", "正在停止...", "Остановка...", "중지 중..."),
    "closing": _s("Encerrando...", "Closing...", "Cerrando...", "Fermeture...", "Schließen...", "Chiusura...", "बंद हो रहा है...", "جارٍ الإغلاق...", "終了しています...", "正在关闭...", "Закрытие...", "종료 중..."),
    "status_configure": _s("Configure os dispositivos e inicie.", "Choose the devices and start.", "Configura los dispositivos e inicia.", "Choisissez les appareils et lancez.", "Wählen Sie die Geräte und starten Sie.", "Scegli i dispositivi e avvia.", "डिवाइस चुनें और शुरू करें।", "اختر الأجهزة وابدأ.", "デバイスを選んで開始してください。", "选择设备后开始。", "Выберите устройства и начните.", "장치를 선택하고 시작하세요."),
    "status_devices_ready": _s("Dispositivos prontos.", "Devices ready.", "Dispositivos listos.", "Appareils prêts.", "Geräte bereit.", "Dispositivi pronti.", "डिवाइस तैयार हैं।", "الأجهزة جاهزة.", "デバイスの準備ができました。", "设备已就绪。", "Устройства готовы.", "장치가 준비되었습니다."),
    "status_devices_missing": _s("Selecione os dispositivos ausentes ou que foram desconectados.", "Select the devices that are missing or were disconnected.", "Selecciona los dispositivos que faltan o se desconectaron.", "Sélectionnez les appareils manquants ou déconnectés.", "Wählen Sie fehlende oder getrennte Geräte aus.", "Seleziona i dispositivi mancanti o scollegati.", "जो डिवाइस गायब या डिस्कनेक्ट हैं उन्हें चुनें।", "اختر الأجهزة الناقصة أو التي فُصلت.", "見つからない、または外れたデバイスを選んでください。", "请选择缺失或已断开的设备。", "Выберите отсутствующие или отключённые устройства.", "없거나 연결이 끊긴 장치를 선택하세요."),
    "status_no_cable": _s("VB-CABLE não encontrado. Instale-o e atualize os dispositivos.", "VB-CABLE was not found. Install it and refresh the devices.", "No se encontró VB-CABLE. Instálalo y actualiza los dispositivos.", "VB-CABLE est introuvable. Installez-le et actualisez les appareils.", "VB-CABLE wurde nicht gefunden. Installieren Sie es und aktualisieren Sie die Geräte.", "VB-CABLE non trovato. Installalo e aggiorna i dispositivi.", "VB-CABLE नहीं मिला। इंस्टॉल करके डिवाइस रीफ़्रेश करें।", "لم يتم العثور على VB-CABLE. ثبّته ثم حدّث الأجهزة.", "VB-CABLE が見つかりません。インストールしてデバイスを更新してください。", "未找到 VB-CABLE。请安装后刷新设备。", "VB-CABLE не найден. Установите его и обновите устройства.", "VB-CABLE을 찾지 못했습니다. 설치 후 장치를 새로고침하세요."),
    "status_no_loopback": _s("WASAPI loopback não encontrado. Instale PyAudioWPatch e verifique o Windows.", "WASAPI loopback was not found. Install PyAudioWPatch and check Windows.", "No se encontró el loopback WASAPI. Instala PyAudioWPatch y revisa Windows.", "Le loopback WASAPI est introuvable. Installez PyAudioWPatch et vérifiez Windows.", "WASAPI-Loopback wurde nicht gefunden. Installieren Sie PyAudioWPatch und prüfen Sie Windows.", "Loopback WASAPI non trovato. Installa PyAudioWPatch e controlla Windows.", "WASAPI loopback नहीं मिला। PyAudioWPatch इंस्टॉल करें और Windows जाँचें।", "لم يتم العثور على WASAPI loopback. ثبّت PyAudioWPatch وتحقق من Windows.", "WASAPI loopback が見つかりません。PyAudioWPatch を入れて Windows を確認してください。", "未找到 WASAPI loopback。请安装 PyAudioWPatch 并检查 Windows。", "WASAPI loopback не найден. Установите PyAudioWPatch и проверьте Windows.", "WASAPI loopback을 찾지 못했습니다. PyAudioWPatch을 설치하고 Windows를 확인하세요."),
    "status_device_gone": _s("Um dispositivo salvo não está disponível; selecione-o novamente.", "A saved device is unavailable; select it again.", "Un dispositivo guardado no está disponible; selecciónalo de nuevo.", "Un appareil enregistré est indisponible ; sélectionnez-le à nouveau.", "Ein gespeichertes Gerät ist nicht verfügbar; wählen Sie es erneut.", "Un dispositivo salvato non è disponibile; selezionalo di nuovo.", "सहेजा हुआ डिवाइस उपलब्ध नहीं है; उसे फिर चुनें।", "جهاز محفوظ غير متاح؛ أعد اختياره.", "保存済みのデバイスが使えません。選び直してください。", "已保存的设备不可用，请重新选择。", "Сохранённое устройство недоступно; выберите его снова.", "저장된 장치를 사용할 수 없습니다. 다시 선택하세요."),
    "status_cloud_denied": _s("Processamento em nuvem não autorizado.", "Cloud processing was not authorized.", "El procesamiento en la nube no fue autorizado.", "Le traitement dans le cloud n'a pas été autorisé.", "Cloud-Verarbeitung wurde nicht erlaubt.", "L'elaborazione cloud non è stata autorizzata.", "क्लाउड प्रोसेसिंग की अनुमति नहीं मिली।", "لم يُسمح بالمعالجة السحابية.", "クラウド処理は許可されませんでした。", "未授权云端处理。", "Облачная обработка не разрешена.", "클라우드 처리가 허용되지 않았습니다."),
    "status_download_local": _s("Baixe os idiomas em Pacotes de idiomas para usar o modo Local.", "Download the languages in Language packs to use Local mode.", "Descarga los idiomas en Paquetes de idiomas para usar el modo Local.", "Téléchargez les langues dans Packs de langues pour le mode Local.", "Laden Sie die Sprachen unter Sprachpakete herunter, um den lokalen Modus zu nutzen.", "Scarica le lingue in Pacchetti lingua per usare la modalità Locale.", "लोकल मोड के लिए भाषा पैक डाउनलोड करें।", "نزّل اللغات من حزم اللغات لاستخدام الوضع المحلي.", "ローカルモードを使うには言語パックをダウンロードしてください。", "使用本地模式前，请在语言包中下载语言。", "Скачайте языки в языковых пакетах, чтобы использовать локальный режим.", "로컬 모드를 쓰려면 언어 팩에서 언어를 받으세요."),
    "status_downloading": _s("Baixando pacotes offline...", "Downloading offline packs...", "Descargando paquetes sin conexión...", "Téléchargement des packs hors ligne...", "Offline-Pakete werden heruntergeladen...", "Download dei pacchetti offline...", "ऑफ़लाइन पैक डाउनलोड हो रहे हैं...", "جارٍ تنزيل الحزم للعمل دون اتصال...", "オフラインパックをダウンロード中...", "正在下载离线包...", "Загрузка офлайн-пакетов...", "오프라인 팩 다운로드 중..."),
    "status_stopping": _s("Parando os fluxos de áudio...", "Stopping the audio streams...", "Deteniendo los flujos de audio...", "Arrêt des flux audio...", "Audiostreams werden gestoppt...", "Arresto dei flussi audio...", "ऑडियो स्ट्रीम रुक रही हैं...", "جارٍ إيقاف تدفقات الصوت...", "音声ストリームを停止しています...", "正在停止音频流...", "Остановка аудиопотоков...", "오디오 스트림 중지 중..."),
    "status_languages_ready": _s("Idiomas prontos. Iniciando...", "Languages ready. Starting...", "Idiomas listos. Iniciando...", "Langues prêtes. Démarrage...", "Sprachen bereit. Start...", "Lingue pronte. Avvio...", "भाषाएँ तैयार हैं। शुरू हो रहा है...", "اللغات جاهزة. جارٍ البدء...", "言語の準備ができました。開始します...", "语言已就绪。正在开始...", "Языки готовы. Запуск...", "언어가 준비되었습니다. 시작하는 중..."),
    "status_cleared": _s("Histórico e cache apagados.", "History and cache cleared.", "Historial y caché borrados.", "Historique et cache effacés.", "Verlauf und Cache gelöscht.", "Cronologia e cache cancellate.", "इतिहास और कैश मिटा दिए गए।", "تم مسح السجل وذاكرة التخزين.", "履歴とキャッシュを消去しました。", "历史和缓存已清除。", "История и кэш удалены.", "기록과 캐시를 지웠습니다."),
    "out_title": _s("Minha voz", "My voice", "Mi voz", "Ma voix", "Meine Stimme", "La mia voce", "मेरी आवाज़", "صوتي", "自分の声", "我的声音", "Мой голос", "내 목소리"),
    "out_subtitle": _s("Para a chamada", "To the call", "Hacia la llamada", "Vers l'appel", "Zum Anruf", "Verso la chiamata", "कॉल की ओर", "إلى المكالمة", "通話へ", "发往通话", "В звонок", "통화로"),
    "in_title": _s("Voz recebida", "Incoming voice", "Voz recibida", "Voix reçue", "Empfangene Stimme", "Voce ricevuta", "आने वाली आवाज़", "الصوت الوارد", "相手の声", "收到的声音", "Входящий голос", "받은 목소리"),
    "in_subtitle": _s("Para o meu fone", "To my headphones", "Hacia mis auriculares", "Vers mon casque", "Zu meinem Kopfhörer", "Alle mie cuffie", "मेरे हेडफ़ोन की ओर", "إلى سماعتي", "自分のヘッドホンへ", "发往我的耳机", "В мои наушники", "내 헤드폰으로"),
    "spoken_language": _s("Idioma falado", "Spoken language", "Idioma hablado", "Langue parlée", "Gesprochene Sprache", "Lingua parlata", "बोली जाने वाली भाषा", "اللغة المنطوقة", "話している言語", "所说语言", "Язык речи", "말하는 언어"),
    "translate_to": _s("Traduzir para", "Translate to", "Traducir a", "Traduire vers", "Übersetzen nach", "Traduci in", "इसमें अनुवाद करें", "الترجمة إلى", "翻訳先", "翻译为", "Перевести на", "번역할 언어"),
    "mic_device": _s("Microfone físico", "Physical microphone", "Micrófono físico", "Microphone physique", "Physisches Mikrofon", "Microfono fisico", "भौतिक माइक्रोफ़ोन", "ميكروفون فعلي", "物理マイク", "物理麦克风", "Физический микрофон", "실제 마이크"),
    "cable_device": _s("Saída virtual (CABLE Input)", "Virtual output (CABLE Input)", "Salida virtual (CABLE Input)", "Sortie virtuelle (CABLE Input)", "Virtueller Ausgang (CABLE Input)", "Uscita virtuale (CABLE Input)", "वर्चुअल आउटपुट (CABLE Input)", "خرج افتراضي (CABLE Input)", "仮想出力（CABLE Input）", "虚拟输出（CABLE Input）", "Виртуальный выход (CABLE Input)", "가상 출력(CABLE Input)"),
    "loopback_device": _s("Áudio recebido (WASAPI loopback)", "Incoming audio (WASAPI loopback)", "Audio recibido (WASAPI loopback)", "Audio reçu (WASAPI loopback)", "Eingehendes Audio (WASAPI-Loopback)", "Audio in arrivo (WASAPI loopback)", "आने वाला ऑडियो (WASAPI loopback)", "الصوت الوارد (WASAPI loopback)", "受信音声（WASAPI loopback）", "接收音频（WASAPI loopback）", "Входящее аудио (WASAPI loopback)", "수신 오디오(WASAPI loopback)"),
    "phones_device": _s("Fone / alto-falante", "Headphones / speakers", "Auriculares / altavoz", "Casque / haut-parleur", "Kopfhörer / Lautsprecher", "Cuffie / altoparlante", "हेडफ़ोन / स्पीकर", "سماعة / مكبر", "ヘッドホン / スピーカー", "耳机 / 扬声器", "Наушники / динамики", "헤드폰 / 스피커"),
    "status_waiting": _s("Aguardando", "Waiting", "En espera", "En attente", "Wartet", "In attesa", "प्रतीक्षा", "قيد الانتظار", "待機中", "等待中", "Ожидание", "대기"),
    "history_title": _s("Histórico desta sessão", "This session", "Historial de esta sesión", "Historique de la session", "Verlauf dieser Sitzung", "Cronologia di questa sessione", "इस सत्र का इतिहास", "سجل هذه الجلسة", "このセッションの履歴", "本次会话记录", "История этой сессии", "이번 세션 기록"),
    "direction_out": _s("EU → CHAMADA", "ME → CALL", "YO → LLAMADA", "MOI → APPEL", "ICH → ANRUF", "IO → CHIAMATA", "मैं → कॉल", "أنا → المكالمة", "自分 → 通話", "我 → 通话", "Я → ЗВОНОК", "나 → 통화"),
    "direction_in": _s("CHAMADA → EU", "CALL → ME", "LLAMADA → YO", "APPEL → MOI", "ANRUF → ICH", "CHIAMATA → IO", "कॉल → मैं", "المكالمة → أنا", "通話 → 自分", "通话 → 我", "ЗВОНОК → Я", "통화 → 나"),
    "clear_data": _s("Limpar dados", "Clear data", "Borrar datos", "Effacer les données", "Daten löschen", "Cancella dati", "डेटा मिटाएँ", "مسح البيانات", "データを消去", "清除数据", "Очистить данные", "데이터 지우기"),
    "devices_loading": _s("Carregando...", "Loading...", "Cargando...", "Chargement...", "Laden...", "Caricamento...", "लोड हो रहा है...", "جارٍ التحميل...", "読み込み中...", "加载中...", "Загрузка...", "불러오는 중..."),
    "devices_none": _s("Nenhum dispositivo encontrado", "No device found", "Ningún dispositivo encontrado", "Aucun appareil trouvé", "Kein Gerät gefunden", "Nessun dispositivo trovato", "कोई डिवाइस नहीं मिला", "لم يتم العثور على جهاز", "デバイスが見つかりません", "未找到设备", "Устройства не найдены", "장치를 찾지 못했습니다"),
    "tests_title": _s("Testes de áudio", "Audio tests", "Pruebas de audio", "Tests audio", "Audiotests", "Test audio", "ऑडियो परीक्षण", "اختبارات الصوت", "音声テスト", "音频测试", "Проверка звука", "오디오 테스트"),
    "tests_subtitle": _s("Confira microfone, fone e saída virtual sem iniciar a tradução. Os testes usam os dispositivos escolhidos na aba Tradução.", "Check the microphone, headphones, and virtual output without starting translation. Tests use the devices chosen on the Translation tab.", "Comprueba micrófono, auriculares y salida virtual sin iniciar la traducción. Las pruebas usan los dispositivos de la pestaña Traducción.", "Vérifiez le micro, le casque et la sortie virtuelle sans lancer la traduction. Les tests utilisent les appareils de l'onglet Traduction.", "Prüfen Sie Mikrofon, Kopfhörer und virtuellen Ausgang, ohne die Übersetzung zu starten. Die Tests nutzen die Geräte im Tab Übersetzung.", "Controlla microfono, cuffie e uscita virtuale senza avviare la traduzione. I test usano i dispositivi della scheda Traduzione.", "अनुवाद शुरू किए बिना माइक, हेडफ़ोन और वर्चुअल आउटपुट जाँचें। परीक्षण अनुवाद टैब के डिवाइस इस्तेमाल करते हैं।", "افحص الميكروفون والسماعة والخرج الافتراضي دون بدء الترجمة. تستخدم الاختبارات أجهزة تبويب الترجمة.", "翻訳を始めずにマイク、ヘッドホン、仮想出力を確認します。テストは翻訳タブで選んだデバイスを使います。", "不开始翻译即可检查麦克风、耳机和虚拟输出。测试使用翻译页所选设备。", "Проверьте микрофон, наушники и виртуальный выход, не запуская перевод. Используются устройства со вкладки перевода.", "번역을 시작하지 않고 마이크, 헤드폰, 가상 출력을 확인합니다. 번역 탭에서 고른 장치를 사용합니다."),
    "tests_devices": _s("Microfone: {mic}\nFone: {phones}\nSaída virtual: {cable}", "Microphone: {mic}\nHeadphones: {phones}\nVirtual output: {cable}", "Micrófono: {mic}\nAuriculares: {phones}\nSalida virtual: {cable}", "Microphone : {mic}\nCasque : {phones}\nSortie virtuelle : {cable}", "Mikrofon: {mic}\nKopfhörer: {phones}\nVirtueller Ausgang: {cable}", "Microfono: {mic}\nCuffie: {phones}\nUscita virtuale: {cable}", "माइक्रोफ़ोन: {mic}\nहेडफ़ोन: {phones}\nवर्चुअल आउटपुट: {cable}", "الميكروفون: {mic}\nالسماعة: {phones}\nالخرج الافتراضي: {cable}", "マイク: {mic}\nヘッドホン: {phones}\n仮想出力: {cable}", "麦克风：{mic}\n耳机：{phones}\n虚拟输出：{cable}", "Микрофон: {mic}\nНаушники: {phones}\nВиртуальный выход: {cable}", "마이크: {mic}\n헤드폰: {phones}\n가상 출력: {cable}"),
    "mic_card_title": _s("Microfone", "Microphone", "Micrófono", "Microphone", "Mikrofon", "Microfono", "माइक्रोफ़ोन", "الميكروفون", "マイク", "麦克风", "Микрофон", "마이크"),
    "mic_card_body": _s("Veja o nível enquanto fala ou grave três segundos e ouça no fone.", "Watch the level while you speak, or record three seconds and hear it in the headphones.", "Mira el nivel mientras hablas o graba tres segundos y escúchalo en los auriculares.", "Regardez le niveau en parlant, ou enregistrez trois secondes et écoutez-les au casque.", "Sehen Sie den Pegel beim Sprechen oder nehmen Sie drei Sekunden auf und hören Sie sie im Kopfhörer.", "Guarda il livello mentre parli oppure registra tre secondi e ascoltali nelle cuffie.", "बोलते समय स्तर देखें, या तीन सेकंड रिकॉर्ड करके हेडफ़ोन पर सुनें।", "راقب المستوى أثناء الكلام، أو سجّل ثلاث ثوانٍ واستمع إليها في السماعة.", "話しながらレベルを見るか、3秒録音してヘッドホンで聴きます。", "说话时查看电平，或录制三秒后在耳机中回放。", "Смотрите уровень, пока говорите, или запишите три секунды и послушайте в наушниках.", "말하면서 레벨을 보거나, 3초를 녹음해 헤드폰으로 듣습니다."),
    "mic_listen": _s("Ouvir nível", "Monitor level", "Ver nivel", "Voir le niveau", "Pegel anzeigen", "Vedi livello", "स्तर सुनें", "مراقبة المستوى", "レベルを見る", "查看电平", "Слушать уровень", "레벨 보기"),
    "mic_stop": _s("Parar nível", "Stop level", "Detener nivel", "Arrêter le niveau", "Pegel stoppen", "Ferma livello", "स्तर रोकें", "إيقاف المستوى", "レベルを止める", "停止电平", "Остановить уровень", "레벨 중지"),
    "mic_record": _s("Gravar 3 segundos", "Record 3 seconds", "Grabar 3 segundos", "Enregistrer 3 secondes", "3 Sekunden aufnehmen", "Registra 3 secondi", "3 सेकंड रिकॉर्ड करें", "تسجيل 3 ثوانٍ", "3秒録音", "录制 3 秒", "Записать 3 секунды", "3초 녹음"),
    "phones_card_title": _s("Fone", "Headphones", "Auriculares", "Casque", "Kopfhörer", "Cuffie", "हेडफ़ोन", "السماعة", "ヘッドホン", "耳机", "Наушники", "헤드폰"),
    "phones_card_body": _s("Toca um sinal curto no fone ou alto-falante escolhido.", "Plays a short tone in the selected headphones or speakers.", "Reproduce un tono corto en los auriculares o el altavoz elegido.", "Joue un court signal dans le casque ou le haut-parleur choisi.", "Spielt einen kurzen Ton im gewählten Kopfhörer oder Lautsprecher.", "Riproduce un tono breve nelle cuffie o nell'altoparlante scelto.", "चुने हुए हेडफ़ोन या स्पीकर पर एक छोटा स्वर बजाता है।", "يشغّل نغمة قصيرة في السماعة المختارة.", "選んだヘッドホンまたはスピーカーで短い音を鳴らします。", "在所选耳机或扬声器中播放一声短提示音。", "Проигрывает короткий сигнал в выбранных наушниках или динамиках.", "선택한 헤드폰이나 스피커로 짧은 음을 냅니다."),
    "phones_play": _s("Tocar no fone", "Play in headphones", "Reproducir en auriculares", "Jouer dans le casque", "Im Kopfhörer abspielen", "Riproduci nelle cuffie", "हेडफ़ोन पर बजाएँ", "تشغيل في السماعة", "ヘッドホンで再生", "在耳机中播放", "Играть в наушниках", "헤드폰에서 재생"),
    "voice_card_title": _s("Tom da voz", "Voice pitch", "Tono de la voz", "Hauteur de la voix", "Stimmton", "Tono della voce", "आवाज़ का स्वर", "طبقة الصوت", "声の高さ", "音高", "Высота голоса", "음성 높낮이"),
    "voice_card_body": _s("Ouça o tom escolhido na barra lateral, primeiro num sinal e depois numa frase sintetizada.", "Hear the pitch chosen in the sidebar, first as a tone and then as a spoken sentence.", "Escucha el tono elegido en la barra lateral, primero como señal y luego como una frase.", "Écoutez la hauteur choisie dans la barre latérale, d'abord en signal puis en phrase.", "Hören Sie die in der Seitenleiste gewählte Tonhöhe, erst als Signal und dann als Satz.", "Ascolta il tono scelto nella barra laterale, prima come segnale e poi come frase.", "साइडबार में चुना स्वर सुनें: पहले एक टोन, फिर एक वाक्य।", "استمع إلى الطبقة المختارة في الشريط الجانبي، أولاً كنغمة ثم كجملة.", "サイドバーで選んだ高さを、まず音で、次に文で聴きます。", "先听侧栏所选音高的提示音，再听一句合成语音。", "Послушайте высоту с боковой панели: сначала сигнал, затем фразу.", "사이드바에서 고른 높이를 먼저 음으로, 그다음 문장으로 듣습니다."),
    "voice_preview": _s("Ouvir o tom", "Preview pitch", "Oír el tono", "Écouter la hauteur", "Tonhöhe hören", "Ascolta il tono", "स्वर सुनें", "سماع الطبقة", "高さを聴く", "试听音高", "Слушать высоту", "높낮이 듣기"),
    "voice_sample": _s("Amostra de voz", "Voice sample", "Muestra de voz", "Échantillon de voix", "Stimmprobe", "Campione di voce", "आवाज़ का नमूना", "عينة صوت", "音声サンプル", "语音样本", "Образец голоса", "음성 샘플"),
    "cable_card_title": _s("Saída virtual", "Virtual output", "Salida virtual", "Sortie virtuelle", "Virtueller Ausgang", "Uscita virtuale", "वर्चुअल आउटपुट", "الخرج الافتراضي", "仮想出力", "虚拟输出", "Виртуальный выход", "가상 출력"),
    "cable_card_body": _s("Envia um sinal curto ao CABLE Input para confirmar o microfone da chamada.", "Sends a short tone to CABLE Input to confirm the call microphone.", "Envía un tono corto a CABLE Input para confirmar el micrófono de la llamada.", "Envoie un court signal vers CABLE Input pour confirmer le micro de l'appel.", "Sendet einen kurzen Ton an CABLE Input, um das Anrufmikrofon zu prüfen.", "Invia un tono breve a CABLE Input per confermare il microfono della chiamata.", "कॉल माइक की पुष्टि के लिए CABLE Input पर एक छोटा स्वर भेजता है।", "يرسل نغمة قصيرة إلى CABLE Input للتأكد من ميكروفون المكالمة.", "通話マイクを確認するため、CABLE Input に短い音を送ります。", "向 CABLE Input 发送短提示音，以确认通话麦克风。", "Отправляет короткий сигнал в CABLE Input, чтобы проверить микрофон звонка.", "통화 마이크를 확인하려고 CABLE Input으로 짧은 음을 보냅니다."),
    "cable_play": _s("Tocar na saída virtual", "Play on virtual output", "Reproducir en la salida virtual", "Jouer sur la sortie virtuelle", "Auf virtuellem Ausgang abspielen", "Riproduci sull'uscita virtuale", "वर्चुअल आउटपुट पर बजाएँ", "تشغيل على الخرج الافتراضي", "仮想出力で再生", "在虚拟输出中播放", "Играть на виртуальном выходе", "가상 출력에서 재생"),
    "test_level": _s("Nível do microfone", "Microphone level", "Nivel del micrófono", "Niveau du microphone", "Mikrofonpegel", "Livello del microfono", "माइक्रोफ़ोन स्तर", "مستوى الميكروفون", "マイクレベル", "麦克风电平", "Уровень микрофона", "마이크 레벨"),
    "test_pipeline_running": _s("Pare a tradução antes de testar o áudio.", "Stop translation before testing audio.", "Detén la traducción antes de probar el audio.", "Arrêtez la traduction avant de tester l'audio.", "Stoppen Sie die Übersetzung, bevor Sie Audio testen.", "Ferma la traduzione prima di provare l'audio.", "ऑडियो परीक्षण से पहले अनुवाद रोकें।", "أوقف الترجمة قبل اختبار الصوت.", "音声テストの前に翻訳を停止してください。", "测试音频前请先停止翻译。", "Остановите перевод перед проверкой звука.", "오디오를 테스트하기 전에 번역을 중지하세요."),
    "test_need_mic": _s("Selecione o microfone na aba Tradução.", "Select the microphone on the Translation tab.", "Selecciona el micrófono en la pestaña Traducción.", "Sélectionnez le microphone dans l'onglet Traduction.", "Wählen Sie das Mikrofon im Tab Übersetzung.", "Seleziona il microfono nella scheda Traduzione.", "अनुवाद टैब में माइक्रोफ़ोन चुनें।", "اختر الميكروفون في تبويب الترجمة.", "翻訳タブでマイクを選んでください。", "请在翻译页选择麦克风。", "Выберите микрофон на вкладке перевода.", "번역 탭에서 마이크를 선택하세요."),
    "test_need_output": _s("Selecione o fone ou alto-falante na aba Tradução.", "Select headphones or speakers on the Translation tab.", "Selecciona auriculares o altavoz en la pestaña Traducción.", "Sélectionnez le casque ou le haut-parleur dans l'onglet Traduction.", "Wählen Sie Kopfhörer oder Lautsprecher im Tab Übersetzung.", "Seleziona cuffie o altoparlante nella scheda Traduzione.", "अनुवाद टैब में हेडफ़ोन या स्पीकर चुनें।", "اختر السماعة في تبويب الترجمة.", "翻訳タブでヘッドホンまたはスピーカーを選んでください。", "请在翻译页选择耳机或扬声器。", "Выберите наушники или динамики на вкладке перевода.", "번역 탭에서 헤드폰이나 스피커를 선택하세요."),
    "test_need_cable": _s("Selecione a saída virtual na aba Tradução.", "Select the virtual output on the Translation tab.", "Selecciona la salida virtual en la pestaña Traducción.", "Sélectionnez la sortie virtuelle dans l'onglet Traduction.", "Wählen Sie den virtuellen Ausgang im Tab Übersetzung.", "Seleziona l'uscita virtuale nella scheda Traduzione.", "अनुवाद टैब में वर्चुअल आउटपुट चुनें।", "اختر الخرج الافتراضي في تبويب الترجمة.", "翻訳タブで仮想出力を選んでください。", "请在翻译页选择虚拟输出。", "Выберите виртуальный выход на вкладке перевода.", "번역 탭에서 가상 출력을 선택하세요."),
    "test_recording": _s("Gravando o microfone...", "Recording the microphone...", "Grabando el micrófono...", "Enregistrement du microphone...", "Mikrofon wird aufgenommen...", "Registrazione del microfono...", "माइक्रोफ़ोन रिकॉर्ड हो रहा है...", "جارٍ تسجيل الميكروفون...", "マイクを録音しています...", "正在录制麦克风...", "Запись микрофона...", "마이크 녹음 중..."),
    "test_playing": _s("Reproduzindo...", "Playing...", "Reproduciendo...", "Lecture...", "Wiedergabe...", "Riproduzione...", "चल रहा है...", "جارٍ التشغيل...", "再生しています...", "正在播放...", "Воспроизведение...", "재생 중..."),
    "test_generating": _s("Gerando a amostra de voz...", "Generating the voice sample...", "Generando la muestra de voz...", "Génération de l'échantillon...", "Stimmprobe wird erzeugt...", "Generazione del campione...", "आवाज़ का नमूना बन रहा है...", "جارٍ إنشاء عينة الصوت...", "音声サンプルを作成しています...", "正在生成语音样本...", "Создание образца голоса...", "음성 샘플 생성 중..."),
    "test_done": _s("Teste concluído.", "Test finished.", "Prueba terminada.", "Test terminé.", "Test abgeschlossen.", "Test completato.", "परीक्षण पूरा हुआ।", "اكتمل الاختبار.", "テストが終わりました。", "测试完成。", "Проверка завершена.", "테스트가 끝났습니다."),
    "voice_sample_text": _s("Olá, esta é uma amostra da voz traduzida.", "Hello, this is a sample of the translated voice.", "Hola, esta es una muestra de la voz traducida.", "Bonjour, ceci est un échantillon de la voix traduite.", "Hallo, dies ist eine Probe der übersetzten Stimme.", "Ciao, questo è un esempio della voce tradotta.", "नमस्ते, यह अनुवादित आवाज़ का एक नमूना है।", "مرحبا، هذه عينة من الصوت المترجم.", "こんにちは。これは翻訳された声のサンプルです。", "你好，这是翻译语音的示例。", "Здравствуйте, это образец переведённого голоса.", "안녕하세요, 이것은 번역된 음성의 샘플입니다."),
    "status_transcribing": _s("Transcrevendo", "Transcribing", "Transcribiendo", "Transcription", "Transkription", "Trascrizione", "लिख रहे हैं", "جارٍ التفريغ", "文字起こし中", "正在转写", "Распознавание", "받아쓰는 중"),
    "status_no_speech": _s("Nenhuma fala reconhecida", "No speech recognized", "No se reconoció habla", "Aucune parole reconnue", "Keine Sprache erkannt", "Nessun parlato riconosciuto", "कोई बोली नहीं पहचानी गई", "لم يتم التعرف على كلام", "音声を認識できませんでした", "未识别到语音", "Речь не распознана", "음성을 인식하지 못했습니다"),
    "status_incoming_down": _s("O retorno da chamada caiu. A sua voz continua sendo traduzida.", "The call return dropped. Your voice is still being translated.", "El retorno de la llamada cayó. Tu voz sigue traduciéndose.", "Le retour de l'appel est tombé. Votre voix continue d'être traduite.", "Die Rückleitung ist ausgefallen. Ihre Stimme wird weiter übersetzt.", "Il ritorno della chiamata è caduto. La tua voce continua a essere tradotta.", "कॉल की वापसी गिर गई। आपकी आवाज़ अभी भी अनुवाद हो रही है।", "سقط رجوع المكالمة. صوتك ما زال يُترجم.", "通話の戻りが切れました。あなたの声は翻訳され続けます。", "通话回传中断了。你的声音仍在翻译。", "Возврат звонка прервался. Ваш голос всё ещё переводится.", "통화 되돌아오기가 끊겼습니다. 내 목소리는 계속 번역됩니다."),
    "status_translating": _s("Traduzindo", "Translating", "Traduciendo", "Traduction", "Übersetzung", "Traduzione", "अनुवाद हो रहा है", "جارٍ الترجمة", "翻訳中", "正在翻译", "Перевод", "번역 중"),
    "status_synthesizing": _s("Sintetizando voz", "Synthesizing voice", "Sintetizando voz", "Synthèse vocale", "Stimme wird erzeugt", "Sintesi vocale", "आवाज़ बन रही है", "جارٍ تركيب الصوت", "音声を合成中", "正在合成语音", "Синтез голоса", "음성 합성 중"),
    "status_ready": _s("Pronto em {seconds}s", "Ready in {seconds}s", "Listo en {seconds}s", "Prêt en {seconds}s", "Fertig in {seconds}s", "Pronto in {seconds}s", "{seconds}s में तैयार", "جاهز خلال {seconds} ث", "{seconds}秒で完了", "{seconds}秒后就绪", "Готово за {seconds} с", "{seconds}초 후 준비"),
    "status_listening": _s("Escuta bidirecional ativa", "Two-way listening is active", "Escucha bidireccional activa", "Écoute bidirectionnelle active", "Beidseitiges Zuhören ist aktiv", "Ascolto bidirezionale attivo", "दोतरफ़ा सुनना सक्रिय है", "الاستماع بالاتجاهين نشط", "双方向の待ち受けが有効です", "双向监听已开启", "Двустороннее прослушивание включено", "양방향 듣기가 켜졌습니다"),
    "status_listening_stopped": _s("Escuta parada", "Listening stopped", "Escucha detenida", "Écoute arrêtée", "Zuhören gestoppt", "Ascolto fermato", "सुनना रुक गया", "توقف الاستماع", "待ち受けを停止しました", "监听已停止", "Прослушивание остановлено", "듣기를 중지했습니다"),
    "status_stop_pending": _s("Parada solicitada; finalizando a operação atual", "Stop requested; finishing the current operation", "Parada solicitada; terminando la operación actual", "Arrêt demandé ; fin de l'opération en cours", "Stopp angefordert; aktueller Vorgang wird beendet", "Arresto richiesto; conclusione dell'operazione", "रोकने का अनुरोध; वर्तमान काम पूरा हो रहा है", "طُلب الإيقاف؛ إنهاء العملية الحالية", "停止を受け付けました。いまの処理を終えています", "已请求停止，正在完成当前操作", "Остановка запрошена; завершаем текущую операцию", "중지를 요청했습니다. 현재 작업을 마무리하는 중"),
    "status_queue_full": _s("Fila cheia; frase antiga descartada", "Queue full; an older phrase was dropped", "Cola llena; se descartó una frase antigua", "File pleine ; une phrase ancienne a été écartée", "Warteschlange voll; ein älterer Satz wurde verworfen", "Coda piena; una frase precedente è stata scartata", "कतार भरी है; पुराना वाक्य हटाया गया", "قائمة الانتظار ممتلئة؛ أُسقطت عبارة أقدم", "待ち行列がいっぱいです。古い文を捨てました", "队列已满，已丢弃较早的一句", "Очередь заполнена; старая фраза отброшена", "대기열이 가득 차 이전 문장을 버렸습니다"),
    "mode_hybrid": _s("Híbrido", "Hybrid", "Híbrido", "Hybride", "Hybrid", "Ibrido", "हाइब्रिड", "هجين", "ハイブリッド", "混合", "Гибрид", "하이브리드"),
    "mode_cloud": _s("Nuvem", "Cloud", "Nube", "Cloud", "Cloud", "Cloud", "क्लाउड", "سحابة", "クラウド", "云端", "Облако", "클라우드"),
    "mode_local": _s("Local", "Local", "Local", "Local", "Lokal", "Locale", "लोकल", "محلي", "ローカル", "本地", "Локально", "로컬"),
    "mode_ai": _s("IA contextual (LLM)", "Contextual AI (LLM)", "IA contextual (LLM)", "IA contextuelle (LLM)", "Kontext-KI (LLM)", "IA contestuale (LLM)", "संदर्भ एआई (LLM)", "ذكاء اصطناعي سياقي (LLM)", "文脈AI（LLM）", "语境 AI（LLM）", "Контекстный ИИ (LLM)", "문맥 AI (LLM)"),
    "stt_label": _s("Reconhecimento de fala", "Speech recognition", "Reconocimiento de voz", "Reconnaissance vocale", "Spracherkennung", "Riconoscimento vocale", "वाक् पहचान", "التعرف على الكلام", "音声認識", "语音识别", "Распознавание речи", "음성 인식"),
    "stt_auto": _s("Automático (pelo hardware)", "Automatic (by hardware)", "Automático (según el equipo)", "Automatique (selon le matériel)", "Automatisch (nach Hardware)", "Automatico (in base all'hardware)", "स्वचालित (हार्डवेयर के अनुसार)", "تلقائي (حسب الجهاز)", "自動（ハードウェアに合わせる）", "自动（按硬件）", "Авто (по оборудованию)", "자동(하드웨어 기준)"),
    "stt_fast": _s("Rápido", "Fast", "Rápido", "Rapide", "Schnell", "Veloce", "तेज़", "سريع", "高速", "快速", "Быстро", "빠르게"),
    "stt_balanced": _s("Equilibrado", "Balanced", "Equilibrado", "Équilibré", "Ausgewogen", "Bilanciato", "संतुलित", "متوازن", "バランス", "均衡", "Сбалансировано", "균형"),
    "stt_accurate": _s("Preciso (ideal com GPU)", "Accurate (best with a GPU)", "Preciso (ideal con GPU)", "Précis (idéal avec GPU)", "Genau (am besten mit GPU)", "Preciso (ideale con GPU)", "सटीक (GPU के साथ बेहतर)", "دقيق (الأفضل مع GPU)", "高精度（GPU推奨）", "精确（建议 GPU）", "Точно (лучше с GPU)", "정확하게(GPU 권장)"),
    "rate_label": _s("Velocidade da fala", "Speech speed", "Velocidad del habla", "Vitesse de la voix", "Sprechtempo", "Velocità della voce", "बोलने की गति", "سرعة الكلام", "話す速さ", "语速", "Скорость речи", "말하기 속도"),
    "rate_hint": _s("Acelera sozinha quando há frases esperando.", "Speeds up on its own when phrases are waiting.", "Se acelera sola cuando hay frases en espera.", "Accélère d'elle-même quand des phrases attendent.", "Wird von selbst schneller, wenn Sätze warten.", "Accelera da sola quando ci sono frasi in attesa.", "वाक्य प्रतीक्षा में हों तो अपने आप तेज़ होती है।", "تتسارع تلقائياً عند وجود جمل منتظرة.", "待っている文があると自動で速くなります。", "有句子排队时会自动加快。", "Сама ускоряется, когда фразы ждут очереди.", "기다리는 문장이 있으면 스스로 빨라집니다."),
    "status_warming": _s("Preparando os modelos de voz...", "Preparing the voice models...", "Preparando los modelos de voz...", "Préparation des modèles vocaux...", "Sprachmodelle werden vorbereitet...", "Preparazione dei modelli vocali...", "आवाज़ मॉडल तैयार हो रहे हैं...", "جارٍ تجهيز نماذج الصوت...", "音声モデルを準備しています...", "正在准备语音模型...", "Подготовка голосовых моделей...", "음성 모델 준비 중..."),
    "dialog_llm_title": _s("IA não configurada", "AI not configured", "IA no configurada", "IA non configurée", "KI nicht eingerichtet", "IA non configurata", "एआई सेट नहीं है", "الذكاء الاصطناعي غير مُعد", "AIが未設定です", "未配置 AI", "ИИ не настроен", "AI가 설정되지 않았습니다"),
    "dialog_llm_body": _s(
        "Cole sua chave gratuita do Groq (console.groq.com/keys).\nEm branco, o Loon traduz como no modo Híbrido.",
        "Paste your free Groq key (console.groq.com/keys).\nLeave blank and Loon translates as in Hybrid mode.",
        "Pega tu clave gratuita de Groq (console.groq.com/keys).\nEn blanco, Loon traduce como en el modo Híbrido.",
        "Collez votre clé Groq gratuite (console.groq.com/keys).\nVide, Loon traduit comme en mode Hybride.",
        "Fügen Sie Ihren kostenlosen Groq-Schlüssel ein (console.groq.com/keys).\nLeer übersetzt Loon wie im Hybridmodus.",
        "Incolla la tua chiave Groq gratuita (console.groq.com/keys).\nVuota, Loon traduce come in modalità Ibrida.",
        "अपनी मुफ़्त Groq कुंजी चिपकाएँ (console.groq.com/keys)।\nखाली छोड़ने पर Loon हाइब्रिड मोड की तरह अनुवाद करता है।",
        "الصق مفتاح Groq المجاني (console.groq.com/keys).\nإذا تُرك فارغًا يترجم Loon كما في الوضع الهجين.",
        "無料の Groq キーを貼り付けてください（console.groq.com/keys）。\n空欄ならハイブリッドと同じ方法で翻訳します。",
        "粘贴免费的 Groq 密钥（console.groq.com/keys）。\n留空时，Loon 按混合模式翻译。",
        "Вставьте бесплатный ключ Groq (console.groq.com/keys).\nЕсли оставить пустым, Loon переводит как в гибридном режиме.",
        "무료 Groq 키를 붙여 넣으세요(console.groq.com/keys).\n비워 두면 Loon은 하이브리드 모드처럼 번역합니다.",
    ),
    "gender_female": _s("Feminina", "Female", "Femenina", "Féminine", "Weiblich", "Femminile", "स्त्री", "نسائية", "女性", "女声", "Женский", "여성"),
    "gender_male": _s("Masculina", "Male", "Masculina", "Masculine", "Männlich", "Maschile", "पुरुष", "رجالية", "男性", "男声", "Мужской", "남성"),
    "dialog_stop_first": _s("Pare a tradução antes de fazer esta alteração.", "Stop translation before making this change.", "Detén la traducción antes de hacer este cambio.", "Arrêtez la traduction avant cette modification.", "Stoppen Sie die Übersetzung vor dieser Änderung.", "Ferma la traduzione prima di questa modifica.", "यह बदलाव करने से पहले अनुवाद रोकें।", "أوقف الترجمة قبل إجراء هذا التغيير.", "この変更の前に翻訳を停止してください。", "进行此更改前请先停止翻译。", "Остановите перевод перед этим изменением.", "이 변경 전에 번역을 중지하세요."),
    "dialog_select_devices": _s("Selecione todos os quatro dispositivos de áudio.", "Select all four audio devices.", "Selecciona los cuatro dispositivos de audio.", "Sélectionnez les quatre appareils audio.", "Wählen Sie alle vier Audiogeräte.", "Seleziona tutti e quattro i dispositivi audio.", "चारों ऑडियो डिवाइस चुनें।", "اختر أجهزة الصوت الأربعة.", "4つの音声デバイスをすべて選んでください。", "请选择全部四个音频设备。", "Выберите все четыре аудиоустройства.", "오디오 장치 네 개를 모두 선택하세요."),
    "dialog_virtual_title": _s("Saída não virtual", "Output is not virtual", "La salida no es virtual", "La sortie n'est pas virtuelle", "Ausgang ist nicht virtuell", "L'uscita non è virtuale", "आउटपुट वर्चुअल नहीं है", "الخرج ليس افتراضياً", "出力が仮想ではありません", "输出不是虚拟设备", "Выход не виртуальный", "출력이 가상이 아닙니다"),
    "dialog_virtual_body": _s("A saída da sua voz não parece ser o VB-CABLE. Deseja continuar?", "Your voice output does not look like VB-CABLE. Continue anyway?", "La salida de tu voz no parece ser VB-CABLE. ¿Deseas continuar?", "La sortie de votre voix ne semble pas être VB-CABLE. Continuer ?", "Der Ausgang Ihrer Stimme scheint nicht VB-CABLE zu sein. Trotzdem fortfahren?", "L'uscita della tua voce non sembra VB-CABLE. Continuare?", "आपकी आवाज़ का आउटपुट VB-CABLE नहीं लगता। फिर भी जारी रखें?", "خرج صوتك لا يبدو VB-CABLE. هل تريد المتابعة؟", "声の出力が VB-CABLE ではないようです。続けますか？", "你的声音输出似乎不是 VB-CABLE。仍要继续吗？", "Выход вашего голоса не похож на VB-CABLE. Продолжить?", "목소리 출력이 VB-CABLE로 보이지 않습니다. 계속할까요?"),
    "dialog_cloud_title": _s("Uso de serviços em nuvem", "Use of cloud services", "Uso de servicios en la nube", "Utilisation des services cloud", "Nutzung von Cloud-Diensten", "Uso di servizi cloud", "क्लाउड सेवाओं का उपयोग", "استخدام الخدمات السحابية", "クラウドサービスの使用", "使用云服务", "Использование облачных служб", "클라우드 서비스 사용"),
    "dialog_cloud_body": _s("Neste modo, textos reconhecidos podem ser enviados ao provedor de tradução e ao Edge TTS. O áudio do microfone continua sendo transcrito localmente. Você autoriza esse processamento?", "In this mode, recognized text may be sent to the translation provider and to Edge TTS. Microphone audio is still transcribed locally. Do you allow this processing?", "En este modo, el texto reconocido puede enviarse al proveedor de traducción y a Edge TTS. El audio del micrófono se transcribe localmente. ¿Autorizas este procesamiento?", "Dans ce mode, le texte reconnu peut être envoyé au service de traduction et à Edge TTS. L'audio du micro reste transcrit localement. Autorisez-vous ce traitement ?", "In diesem Modus kann erkannter Text an den Übersetzungsdienst und an Edge TTS gesendet werden. Das Mikrofon bleibt lokal transkribiert. Erlauben Sie diese Verarbeitung?", "In questa modalità il testo riconosciuto può essere inviato al servizio di traduzione e a Edge TTS. L'audio del microfono resta trascritto in locale. Autorizzi questa elaborazione?", "इस मोड में पहचाना गया पाठ अनुवाद सेवा और Edge TTS को जा सकता है। माइक ऑडियो स्थानीय रहता है। क्या आप इसकी अनुमति देते हैं?", "في هذا الوضع قد يُرسل النص المتعرَّف عليه إلى مزود الترجمة وEdge TTS. يبقى صوت الميكروفون محلياً. هل تسمح بهذه المعالجة؟", "このモードでは認識したテキストが翻訳サービスと Edge TTS に送られることがあります。マイク音声の文字起こしはローカルのままです。許可しますか？", "此模式下，识别出的文本可能会发送到翻译服务和 Edge TTS。麦克风音频仍在本地转写。是否允许此处理？", "В этом режиме распознанный текст может уйти поставщику перевода и в Edge TTS. Аудио микрофона по-прежнему распознаётся локально. Разрешить обработку?", "이 모드에서는 인식된 텍스트가 번역 서비스와 Edge TTS로 전송될 수 있습니다. 마이크 오디오는 계속 로컬에서 받아씁니다. 이 처리를 허용할까요?"),
    "dialog_download_title": _s("Baixar idiomas", "Download languages", "Descargar idiomas", "Télécharger les langues", "Sprachen herunterladen", "Scarica lingue", "भाषाएँ डाउनलोड करें", "تنزيل اللغات", "言語をダウンロード", "下载语言", "Скачать языки", "언어 다운로드"),
    "dialog_download_body": _s("O modo Local precisa baixar estes idiomas uma vez, sem mensalidade:\n\n{languages}\n\nDeseja baixar agora?", "Local mode needs to download these languages once, with no subscription:\n\n{languages}\n\nDownload now?", "El modo Local necesita descargar estos idiomas una vez, sin suscripción:\n\n{languages}\n\n¿Descargar ahora?", "Le mode Local doit télécharger ces langues une fois, sans abonnement :\n\n{languages}\n\nTélécharger maintenant ?", "Der lokale Modus muss diese Sprachen einmal herunterladen, ohne Abo:\n\n{languages}\n\nJetzt herunterladen?", "La modalità Locale deve scaricare queste lingue una volta, senza abbonamento:\n\n{languages}\n\nScaricare ora?", "लोकल मोड को ये भाषाएँ एक बार डाउनलोड करनी हैं, बिना सदस्यता के:\n\n{languages}\n\nअभी डाउनलोड करें?", "يحتاج الوضع المحلي إلى تنزيل هذه اللغات مرة واحدة دون اشتراك:\n\n{languages}\n\nهل تريد التنزيل الآن؟", "ローカルモードでは次の言語を一度だけ、サブスクリプションなしでダウンロードします。\n\n{languages}\n\n今ダウンロードしますか？", "本地模式需要一次性下载这些语言，没有订阅费：\n\n{languages}\n\n现在下载吗？", "Локальному режиму нужно один раз скачать эти языки, без подписки:\n\n{languages}\n\nСкачать сейчас?", "로컬 모드는 구독 없이 이 언어를 한 번 받아야 합니다.\n\n{languages}\n\n지금 받을까요?"),
    "dialog_clear_title": _s("Apagar dados", "Delete data", "Borrar datos", "Effacer les données", "Daten löschen", "Cancella dati", "डेटा मिटाएँ", "مسح البيانات", "データを消去", "删除数据", "Удалить данные", "데이터 삭제"),
    "dialog_clear_body": _s("Apagar o histórico local, o cache de voz e o histórico desta sessão?", "Delete the local history, the voice cache, and this session's transcript?", "¿Borrar el historial local, la caché de voz y el historial de esta sesión?", "Effacer l'historique local, le cache vocal et l'historique de cette session ?", "Lokalen Verlauf, Sprachcache und den Verlauf dieser Sitzung löschen?", "Cancellare la cronologia locale, la cache vocale e la cronologia di questa sessione?", "स्थानीय इतिहास, आवाज़ कैश और इस सत्र का इतिहास मिटाएँ?", "هل تريد مسح السجل المحلي وذاكرة الصوت وسجل هذه الجلسة؟", "ローカル履歴、音声キャッシュ、このセッションの履歴を消去しますか？", "删除本地历史、语音缓存和本次会话记录吗？", "Удалить локальную историю, кэш голоса и историю этой сессии?", "로컬 기록, 음성 캐시, 이번 세션 기록을 지울까요?"),
    "packs_title": _s("Idiomas para uso offline", "Languages for offline use", "Idiomas para uso sin conexión", "Langues pour l'usage hors ligne", "Sprachen für die Offline-Nutzung", "Lingue per l'uso offline", "ऑफ़लाइन उपयोग के लिए भाषाएँ", "لغات للعمل دون اتصال", "オフライン用の言語", "离线使用的语言", "Языки для офлайн-режима", "오프라인용 언어"),
    "dialog_missing_voice_title": _s("Falta a voz no Windows", "Windows has no voice for this", "Falta la voz en Windows", "La voix manque dans Windows", "Windows hat keine Stimme dafür", "Manca la voce in Windows", "Windows में यह आवाज़ नहीं है", "لا توجد صوت في Windows", "Windows にこの音声がありません", "Windows 没有这个语音", "В Windows нет этого голоса", "Windows에 이 음성이 없습니다"),
    "dialog_missing_voice_body": _s("A tradução vai aparecer escrita, mas estes idiomas não saem falados:\n\n{languages}\n\nO pacote do Loon só traduz. A voz fica em Configurações, Hora e idioma, Idioma e região, Conversão de texto em fala.", "The translation will still be written, but these languages will not be spoken:\n\n{languages}\n\nThe Loon pack only translates. The voice is installed in Settings, Time & language, Language & region, Text-to-speech.", "La traducción se escribirá, pero estos idiomas no se hablarán:\n\n{languages}\n\nEl paquete de Loon solo traduce. La voz se instala en Configuración, Hora e idioma, Idioma y región, Texto a voz.", "La traduction sera écrite, mais ces langues ne seront pas parlées :\n\n{languages}\n\nLe pack Loon ne fait que traduire. La voix s'installe dans Paramètres, Heure et langue, Langue et région, Synthèse vocale.", "Die Übersetzung erscheint als Text, aber diese Sprachen werden nicht gesprochen:\n\n{languages}\n\nDas Loon-Paket übersetzt nur. Die Stimme liegt unter Einstellungen, Zeit und Sprache, Sprache und Region, Text-zu-Sprache.", "La traduzione resterà scritta, ma queste lingue non verranno lette:\n\n{languages}\n\nIl pacchetto Loon traduce soltanto. La voce si installa in Impostazioni, Ora e lingua, Lingua e area geografica, Sintesi vocale.", "अनुवाद लिखा रहेगा, लेकिन ये भाषाएँ बोली नहीं जाएँगी:\n\n{languages}\n\nLoon पैक केवल अनुवाद करता है। आवाज़ सेटिंग्स, समय और भाषा, भाषा और क्षेत्र, पाठ-से-वाक् में लगती है।", "ستظهر الترجمة مكتوبة، لكن هذه اللغات لن تُنطق:\n\n{languages}\n\nحزمة Loon تترجم فقط. الصوت يُثبَّت من الإعدادات، الوقت واللغة، اللغة والمنطقة، تحويل النص إلى كلام.", "翻訳は文字で残りますが、次の言語は話されません。\n\n{languages}\n\nLoon のパックは翻訳だけです。音声は設定、時刻と言語、言語と地域、テキスト読み上げで入れます。", "翻译仍会写成文字，但这些语言不会被朗读：\n\n{languages}\n\nLoon 的语言包只负责翻译。语音要在设置、时间和语言、语言和区域、文本转语音里安装。", "Перевод останется текстом, но эти языки не будут произнесены:\n\n{languages}\n\nПакет Loon только переводит. Голос ставится в Параметрах, Время и язык, Язык и регион, Преобразование текста в речь.", "번역은 글로 남지만 이 언어는 소리로 나오지 않습니다.\n\n{languages}\n\nLoon 팩은 번역만 합니다. 음성은 설정, 시간 및 언어, 언어 및 지역, 텍스트 음성 변환에서 설치합니다."),
    "error_missing_voice": _s("Sem voz de {language} no Windows. A frase foi traduzida e escrita, mas não foi falada.", "Windows has no {language} voice. The line was translated and written, but not spoken.", "Windows no tiene voz de {language}. La frase se tradujo y se escribió, pero no se habló.", "Windows n'a pas de voix {language}. La phrase a été traduite et écrite, mais pas dite.", "Windows hat keine Stimme für {language}. Der Satz wurde übersetzt und geschrieben, aber nicht gesprochen.", "Windows non ha la voce {language}. La frase è stata tradotta e scritta, ma non letta.", "Windows में {language} की आवाज़ नहीं है। वाक्य अनुवादित और लिखा गया, बोला नहीं गया।", "لا توجد صوت {language} في Windows. تُرجمت الجملة وكُتبت ولم تُنطق.", "Windows に{language}の音声がありません。文は翻訳されて書かれましたが、話されませんでした。", "Windows 没有{language}语音。这句话已翻译并写下，但没有朗读。", "В Windows нет голоса {language}. Фраза переведена и записана, но не произнесена.", "Windows에 {language} 음성이 없습니다. 문장은 번역되어 적혔지만 말하지 않았습니다."),
    "packs_intro": _s("Cada idioma instala os pares com inglês e pode ser usado sem mensalidade. Os modelos são de terceiros. Esse download não instala a voz falada do Windows.", "Each language installs the pairs with English and can be used with no subscription. The models belong to third parties.", "Cada idioma instala los pares con inglés y puede usarse sin suscripción. Los modelos son de terceros.", "Chaque langue installe les paires avec l'anglais et s'utilise sans abonnement. Les modèles viennent de tiers.", "Jede Sprache installiert die Paare mit Englisch und braucht kein Abo. Die Modelle stammen von Dritten.", "Ogni lingua installa le coppie con l'inglese e si usa senza abbonamento. I modelli sono di terze parti.", "हर भाषा अंग्रेज़ी के साथ जोड़े इंस्टॉल करती है और बिना सदस्यता चलती है। मॉडल तीसरे पक्ष के हैं।", "تثبّت كل لغة الأزواج مع الإنجليزية ويمكن استخدامها دون اشتراك. النماذج من أطراف أخرى.", "各言語は英語との対をインストールし、サブスクリプションなしで使えます。モデルは第三者のものです。", "每种语言会安装与英语的互译包，无需订阅。模型来自第三方。", "Каждый язык ставит пары с английским и работает без подписки. Модели принадлежат третьим сторонам.", "각 언어는 영어 쌍을 설치하며 구독 없이 쓸 수 있습니다. 모델은 제3자 것입니다."),
    "pack_download": _s("Baixar", "Download", "Descargar", "Télécharger", "Herunterladen", "Scarica", "डाउनलोड", "تنزيل", "ダウンロード", "下载", "Скачать", "다운로드"),
    "pack_installed": _s("Instalado", "Installed", "Instalado", "Installé", "Installiert", "Installato", "इंस्टॉल है", "مثبّت", "インストール済み", "已安装", "Установлен", "설치됨"),
    "pack_missing": _s("Não instalado", "Not installed", "No instalado", "Non installé", "Nicht installiert", "Non installato", "इंस्टॉल नहीं", "غير مثبّت", "未インストール", "未安装", "Не установлен", "설치 안 됨"),
    "pack_downloading": _s("Baixando...", "Downloading...", "Descargando...", "Téléchargement...", "Download...", "Download...", "डाउनलोड हो रहा है...", "جارٍ التنزيل...", "ダウンロード中...", "下载中...", "Загрузка...", "다운로드 중..."),
    "pack_retry": _s("Tentar novamente", "Try again", "Reintentar", "Réessayer", "Erneut versuchen", "Riprova", "फिर कोशिश करें", "حاول مرة أخرى", "再試行", "重试", "Повторить", "다시 시도"),
    "pack_failed": _s("Falha na instalação", "Installation failed", "Fallo en la instalación", "Échec de l'installation", "Installation fehlgeschlagen", "Installazione non riuscita", "इंस्टॉलेशन विफल", "فشل التثبيت", "インストールに失敗しました", "安装失败", "Ошибка установки", "설치 실패"),
    "pack_ready_for": _s("{language} disponível offline", "{language} available offline", "{language} disponible sin conexión", "{language} disponible hors ligne", "{language} offline verfügbar", "{language} disponibile offline", "{language} ऑफ़लाइन उपलब्ध", "{language} متاحة دون اتصال", "{language} はオフラインで使えます", "{language} 可离线使用", "{language} доступен офлайн", "{language} 오프라인 사용 가능"),
    "provider_cultural": _s("equivalência cultural", "cultural equivalence", "equivalencia cultural", "équivalence culturelle", "kulturelle Entsprechung", "equivalenza culturale", "सांस्कृतिक समतुल्यता", "مكافئ ثقافي", "文化的な言い換え", "文化等效", "культурное соответствие", "문화적 등가"),
    "provider_same": _s("sem tradução", "no translation", "sin traducción", "sans traduction", "ohne Übersetzung", "senza traduzione", "बिना अनुवाद", "بدون ترجمة", "翻訳なし", "无需翻译", "без перевода", "번역 없음"),
    "error_prefix": _s("Erro:", "Error:", "Error:", "Erreur :", "Fehler:", "Errore:", "त्रुटि:", "خطأ:", "エラー:", "错误：", "Ошибка:", "오류:"),
    "error_clear": _s("Não foi possível apagar os dados: {message}", "Could not delete the data: {message}", "No se pudieron borrar los datos: {message}", "Impossible d'effacer les données : {message}", "Daten konnten nicht gelöscht werden: {message}", "Impossibile cancellare i dati: {message}", "डेटा नहीं मिटा: {message}", "تعذر مسح البيانات: {message}", "データを消去できませんでした: {message}", "无法删除数据：{message}", "Не удалось удалить данные: {message}", "데이터를 지우지 못했습니다: {message}"),
    "error_devices": _s("Não foi possível listar os dispositivos: {message}", "Could not list the devices: {message}", "No se pudieron enumerar los dispositivos: {message}", "Impossible de lister les appareils : {message}", "Geräte konnten nicht aufgelistet werden: {message}", "Impossibile elencare i dispositivi: {message}", "डिवाइस सूची नहीं बनी: {message}", "تعذر سرد الأجهزة: {message}", "デバイスを列挙できませんでした: {message}", "无法列出设备：{message}", "Не удалось получить список устройств: {message}", "장치 목록을 가져오지 못했습니다: {message}"),
    "error_playback": _s("O fone recusou o áudio. Ele pode ter mudado para o modo viva-voz. Espere um segundo e tente de novo. Se continuar, escolha os alto-falantes.", "The headphones rejected the audio. They may have switched to hands-free mode. Wait a second and try again. If it continues, choose the speakers.", "Los auriculares rechazaron el audio. Pueden haber pasado al modo manos libres. Espera un segundo e inténtalo de nuevo. Si sigue, elige los altavoces.", "Le casque a refusé l'audio. Il est peut-être passé en mode mains libres. Attendez une seconde et réessayez. Si cela continue, choisissez les haut-parleurs.", "Der Kopfhörer hat den Ton abgelehnt. Er ist vielleicht in den Freisprechmodus gewechselt. Warten Sie eine Sekunde und versuchen Sie es erneut. Wenn es bleibt, wählen Sie die Lautsprecher.", "Le cuffie hanno rifiutato l'audio. Potrebbero essere passate al viva voce. Attendi un secondo e riprova. Se continua, scegli gli altoparlanti.", "हेडफ़ोन ने आवाज़ अस्वीकार कर दी। वह हैंड्स-फ़्री मोड में चला गया हो सकता है। एक सेकंड रुककर फिर कोशिश करें। जारी रहे तो स्पीकर चुनें।", "رفضت السماعة الصوت. ربما تحولت إلى وضع حر اليدين. انتظر ثانية وحاول مرة أخرى. إذا استمر، اختر مكبرات الصوت.", "ヘッドホンが音声を拒否しました。ハンズフリーに切り替わった可能性があります。少し待って再試行してください。続く場合はスピーカーを選んでください。", "耳机拒绝了音频。它可能已切换到免提模式。请稍等再试。如果继续出现，请改用扬声器。", "Наушники отклонили звук. Возможно, они перешли в режим громкой связи. Подождите секунду и повторите. Если повторится, выберите колонки.", "헤드폰이 소리를 거부했습니다. 핸즈프리로 바뀌었을 수 있습니다. 잠시 후 다시 시도하세요. 계속되면 스피커를 선택하세요."),
    "error_packs_check": _s("Não foi possível verificar os pacotes de idioma. Abra Pacotes de idiomas e tente novamente.\n\n{message}", "Could not check the language packs. Open Language packs and try again.\n\n{message}", "No se pudieron comprobar los paquetes. Abre Paquetes de idiomas e inténtalo de nuevo.\n\n{message}", "Impossible de vérifier les packs. Ouvrez Packs de langues et réessayez.\n\n{message}", "Sprachpakete konnten nicht geprüft werden. Öffnen Sie Sprachpakete und versuchen Sie es erneut.\n\n{message}", "Impossibile verificare i pacchetti. Apri Pacchetti lingua e riprova.\n\n{message}", "भाषा पैक जाँचे नहीं जा सके। भाषा पैक खोलकर फिर कोशिश करें।\n\n{message}", "تعذر التحقق من حزم اللغات. افتح حزم اللغات وحاول مرة أخرى.\n\n{message}", "言語パックを確認できませんでした。言語パックを開いて再試行してください。\n\n{message}", "无法检查语言包。请打开语言包后重试。\n\n{message}", "Не удалось проверить языковые пакеты. Откройте языковые пакеты и повторите.\n\n{message}", "언어 팩을 확인하지 못했습니다. 언어 팩을 열고 다시 시도하세요.\n\n{message}"),
    "error_pack_download": _s("Não foi possível baixar o idioma. Verifique a internet e tente novamente.\n\n{message}", "Could not download the language. Check the internet and try again.\n\n{message}", "No se pudo descargar el idioma. Revisa internet e inténtalo de nuevo.\n\n{message}", "Impossible de télécharger la langue. Vérifiez internet et réessayez.\n\n{message}", "Sprache konnte nicht heruntergeladen werden. Prüfen Sie das Internet und versuchen Sie es erneut.\n\n{message}", "Impossibile scaricare la lingua. Controlla internet e riprova.\n\n{message}", "भाषा डाउनलोड नहीं हुई। इंटरनेट जाँचकर फिर कोशिश करें।\n\n{message}", "تعذر تنزيل اللغة. تحقق من الإنترنت وحاول مرة أخرى.\n\n{message}", "言語をダウンロードできませんでした。ネットを確認して再試行してください。\n\n{message}", "无法下载语言。请检查网络后重试。\n\n{message}", "Не удалось скачать язык. Проверьте интернет и повторите.\n\n{message}", "언어를 받지 못했습니다. 인터넷을 확인하고 다시 시도하세요.\n\n{message}"),
}


def locale_code(language_name: str) -> str:
    raw = LANGUAGES_DICT.get(language_name, "pt")
    if raw in {"", "auto"}:
        return "pt"
    if raw.lower().startswith("zh"):
        return "zh"
    base = raw.lower().split("-")[0]
    return base if base in LOCALES else "en"


def ui_text(language_name: str, key: str) -> str:
    entry = STRINGS.get(key)
    if not entry:
        return key
    code = locale_code(language_name)
    return entry.get(code) or entry.get("en") or entry.get("pt") or key


def language_label(canonical: str, ui_language: str) -> str:
    labels = LANGUAGE_NAMES.get(canonical)
    if not labels:
        return canonical
    return labels.get(locale_code(ui_language), canonical)


def language_choices(ui_language: str, *, include_auto: bool = True) -> list[str]:
    names = [name for name in LANGUAGES_DICT if include_auto or name != "Auto"]
    return [language_label(name, ui_language) for name in names]


def canonical_language(label: str, ui_language: str) -> str:
    if label in LANGUAGES_DICT:
        return label
    code = locale_code(ui_language)
    for name, labels in LANGUAGE_NAMES.items():
        if labels.get(code) == label:
            return name
    for name, labels in LANGUAGE_NAMES.items():
        if label in labels.values():
            return name
    return label


def choice_label(mapping: dict[str, str], canonical: str, ui_language: str, fallback: str) -> str:
    key = mapping.get(canonical) or mapping[fallback]
    return ui_text(ui_language, key)


def choice_values(mapping: dict[str, str], ui_language: str) -> list[str]:
    return [ui_text(ui_language, key) for key in mapping.values()]


def canonical_choice(
    label: str,
    mapping: dict[str, str],
    ui_language: str,
    fallback: str,
) -> str:
    for canonical, key in mapping.items():
        if label == canonical or label == ui_text(ui_language, key):
            return canonical
    return fallback
